### ISSUE TITLE
perltidy fails to delete backup file

### ISSUE THREAD

**Issue by bmartin** [perltidy/perltidy#109]
See this line:

https://github.com/perltidy/perltidy/blob/d5f0ff670e29ec49ad1956ad862026aa8951fa23/lib/Perl/Tidy.pm#L1234
```perl
        if ( !-s $output_file && -s $backup_file && $delete_backup == 1 ) {
```

That seems to make the assumption that `$output_file` is a file name. However, earlier in the function you see:

https://github.com/perltidy/perltidy/blob/d5f0ff670e29ec49ad1956ad862026aa8951fa23/lib/Perl/Tidy.pm#L1132

```perl
    # NOTES:
    # - Die immediately on any error.
    # - $output_file is actually an ARRAY ref
```

The result is an error like:

~~~
$ perltidy -b -bext=/ test.pl
output file 'ARRAY(0x34afa40)' missing or zero length; original 'test.pl.bak' not deleted
~~~

**Comment by bmartin** [comment]
I suspect the solution may be as simple as changing `$ouput_file` to `$input_file` on line 1234 and the next line.

**Comment by shancock9** [comment]
Ben, thanks for reporting this problem and the fix. It looks like this was an oversight in the update for git #103. A release to CPAN should be in a couple of weeks. Meanwhile, the update is in tagged version 20220613.06 

https://github.com/perltidy/perltidy/tags

**Comment by bmartin** [comment]
Thank you!

**Comment by shancock9** [comment]
Version 20221112 has this update.
