### ISSUE TITLE
Strange behaviour of -vt option

### ISSUE THREAD

**Issue by elcamlost** [perltidy/perltidy#11]
I have a snippet

```perl
$graphite->incr_bulk(
    "count.requests.${graphite_error_key}.some_long_key.subkey"
);
```

**perltidy -vt=0 -vtc=0** gives
```perl
$graphite->incr_bulk(
    "count.requests.${graphite_error_key}.some_long_key.subkey");
```

So line is not broken before closing token **)** with explicit instruction to always break a line before a closing token given with **-vtc=0** option.

Do I understand vtc option incorrectly?

**Comment by shancock9** [comment]
Short lengths of code (2 lines here) often follow other rules. From the man
page on vtc:
Finally, please note that these vertical tightness flags are merely hints
to the formatter, and it cannot
               always follow them.  Things which make it difficult or
impossible include comments, blank lines, blocks of
               code within a list, and possibly the lack of the -lp
parameter.  Also, these flags may be ignored for very
               small lists (2 or 3 lines in length).

**Comment by elcamlost** [comment]
So, for now there is now option, that will preserve line breaks in this snippet except **-lp**?

**Comment by shancock9** [comment]
No, unless you want to forced a break by putting a comma at the end of the
second line and using --break-at-old-comma-breakpoints

**Comment by elcamlost** [comment]
Got it. Thanks a lot for your help.
