### ISSUE TITLE
goto - unless - unless - if

### ISSUE THREAD

**Issue by jidanni** [perltidy/perltidy#116]
Shouldn't the `if` line up with the `unless`?
```
    goto OK unless $_ % 10;
    next    unless $_ > 50;
    next    unless $_ < 70;
    next if $_ % 2;
```
v20220613

**Comment by shancock9** [comment]
Yes, and actually the code is in place to do that but was being bypassed.  I tested it and it works. So I will activate it in the next release, but it will need a new control switch since this would change existing formatting.

**Comment by shancock9** [comment]
Version 20230701 at CPAN has this update
