### ISSUE TITLE
raise warning if format skipping starting marker is useless

### ISSUE THREAD

**Issue by XSven** [perltidy/perltidy#118]
I wanted to figure out why perltidy does not format my source code

```
#<<<
use strict; use warnings;
#<<<

# code that should be formatted
```

Unfortunately perltidy does nothing. The problem is that I have used by accident two times the format skipping starting marker #<<< instead of the format skipping end marker #>>>. Could perltidy raise a warning in such cases?

**Comment by shancock9** [comment]
Yes, I can add that warning. 

It is worth noting that it is possible to find out which lines are being skipped by writing a .LOG file, with the -g parameter.  In this example it would write
```
Line 1: Entering format-skipping section
```
but there would be no corresponding message for exiting format-skipping.

**Comment by XSven** [comment]
according to the changes this improvement is part of the 20230701 release
