### ISSUE TITLE
Perltidy incorrectly count length unicode comments

### ISSUE THREAD

**Issue by elcamlost** [perltidy/perltidy#12]
Snippet
```perl
sub test {

    # 40 symbol length 40 symbol length
    return test_2(shift);
}
```
**perltidy -l 40** produces
```perl
sub test {

    # 40 symbol length 40 symbol length
    return test_2(shift);
}
```

The same snippet but with utf8 comment
```perl
sub test {

    # 40 символов utf8 40 символов utf8
    return test_2(shift);
}
```

**perltidy -l 40** produces
```perl
sub test {

# 40 символов utf8 40 символов utf8
    return test_2(shift);
}
```

**Comment by shancock9** [comment]
You probably need the -utf8 flag here

**Comment by elcamlost** [comment]
Thanks, -utf8 helps. 
[Perlcritic](https://metacpan.org/pod/Perl::Critic::Policy::CodeLayout::RequireTidyCode) plugin now insists that code is not tidy, but this is probably plugin problem. I'll try to investigate it further.
