### ISSUE TITLE
Block brace tightness does not detect print blocks

### ISSUE THREAD

**Issue by jbrobst** [perltidy/perltidy#121]
Consider this snippet from [print's documentation][1]:

```perl
print { $files[$i] } "stuff\n";
print { $OK ? *STDOUT : *STDERR } "stuff\n";
```

This should remain unchanged with `-bbt=0`, but `perltidy -bt=2 -bbt=0` gives:

```perl
print {$files[$i]} "stuff\n";
print {$OK ? *STDOUT : *STDERR} "stuff\n";
```

So, it seems that these blocks are being formatted according to `-bt` rather than `-bbt`. This is also the case for other built-in functions that accept an optional indirect object: `printf`, `say`, `exec`, and `system`.

[1]: https://perldoc.perl.org/functions/print

**Comment by shancock9** [comment]
As you noticed, perltidy does not always follow whitespace controls for print and other functions that accept an optional indirect object. For an explanation, please see the following sections of the manual:

```
Note1: Perltidy does always follow whitespace controls

Note2: Perltidy's whitespace rules are not perfect
```

**Comment by jbrobst** [comment]
I've read those sections and understand the difficulties discussed there, but it still seems to me that code blocks following these functions can be unambiguously parsed as such and formatted according to `bbt` without changing program behavior. Is there an example where this is not the case?

**Comment by shancock9** [comment]
I'm not aware of one, but would not be surprised if there were an issue in some older versions of Perl, which Perltidy has to support.

**Comment by shancock9** [comment]
I'm testing a fix for this, and if it survives testing it will be in the next release.

**Comment by shancock9** [comment]
Testing showed that allowing perltidy's controls for code blocks to apply to small blocks such as those after a ``print`` keyword does not work well. Besides changing a lot of existing formatting, this can cause undesirable line breaks when formatting comes under stress due to line length limits being reached. So this change will not be made. But a note of explanation will be added to the manual.

**Comment by jbrobst** [comment]
Thanks for looking into a fix.

For older Perl versions: the syntax was added in Perl 5, and before that a brace following these functions would result in a syntax error. For any Perl 5+, I can't see any way a brace following these functions would parse as anything but the `block` form of the `indirob` nonterminal, so formatting should be safe.

Regarding the formatting and line breaks for small blocks following these functions, couldn't they be treated in a similar manner to small `grep`/`map`/`sort` blocks?

**Comment by shancock9** [comment]
Or it could be a hash ref brace, as in ``print {1,2},3,"\n";``, although that is not very useful following a ``print``.

Following the ``sort/map/grep`` model would not work.  But it might be possible to introduce a toggle switch to control 
just the horizontal spacing for these special blocks.  One value would say follow the spacing controls for
hash braces (current default), and the other would say follow the spacing controls for block braces.  The main difficulty
with this would be do define to which special blocks this applies. I'll think about that.

**Comment by shancock9** [comment]
I've tentatively added a new flag **-xbt** to handle this issue.  It appears to work okay and will be in the next release to CPAN unless some problems are encountered. It is in the [tagged version 20230309.03](https://github.com/perltidy/perltidy/tags). The description is as follows:

- **-xbt**,   **--extended-block-tightness**

    Perltidy has two controls for spacing within curly braces, namely
    **-block-brace-tightness=n** for code block braces and **-brace-tightness=n** for
    all other braces.

    Curly braces which are considered by perltidy to contain code blocks for
    formatting purposes exclude some of the code blocks used by Perl mainly for
    isolating terms. These include curly braces following a keyword where an
    indirect object might occur, or curly braces following certain special symbols.  For
    example, perltidy does not mark the following braces as code block braces:

        print {*STDERR} $message;
        return @{$self};

    Consequently, the spacing within these small braced containers follows the flag
    **--brace-tightness=n** rather than **--block-brace-tightness=n**, as one might
    expect.

    If desired, these small blocks can be made to instead follow the spacing
    defined by the **--block-brace-tightness=n** flag by seting
    **--extended-block-tightness**.

    Note that if the two flags **-bbt=n** and **-bt=n** have the same value
    **n** then there would be no reason to set this flag.

There is a companion flag which can be used to modify its behavior:

- **-xbtl=s**,   **--extended-block-tightness-list=s**

    By default, the previous parameter **-xbt** applies to curly braces preceded by
    the keywords

        print printf exec system say

    and by the special symbols

        $ @ % & * $#

    This default behavior can be changed as follows.  To restrict **-xbt** to apply
    to just the above keywords use

        -xbtl=k

    and to restrict it to apply to just the above special type symbols use

        -xbtl=t

    More generally, to restrict it to specific keywords or type symbols in the
    above lists, enter them in the parameter list **s**. For example, the following
    restricts it apply to just the keywords **print** and **say**:

        -xbtl="print say"

    Note that this parameter merely changes the way that the parameter
    **--extended-block-tightness** works. It has no effect unless
    **--extended-block-tightness** is actually set.

**Comment by jbrobst** [comment]
Tried these options out on a few scripts and had no issues. Thanks for the fix!

**Comment by Julien-Elie** [comment]
I've just tried this new feature.

Using `-xbt` turns
`our $newsuser = ${runasuser};`
into:
`our $newsuser = ${ runasuser };`

Shouldn't it remain untouched?

I see that other constructions like:
`our $innd = "${newsbin}/innd";`
are kept unchanged, so I believe it should also not be changed for `${runasuser}` alone without surrounding quotes (`"${runasuser}"`).
Otherwise, shouldn't `"${newsbin}/innd"` have been changed to `"${ newsbin }/innd"`?

**Comment by shancock9** [comment]
Thanks for testing the tentative new option ``-xbt``. I appreciate the feedback.

This has a companion configuration parameter ``-xbtl=s``, where ``s`` identifies to which braces it applies (listed above in the git #121 discussion). The default configuration is basically ``-xbtl='k t'``, which means that the ``-xbt`` parameter applies to braces preceded by either a keyword or special type character. It looks like you would want to set ``-xbtl=k`` to prevent a brace preceded by a special type character such as ``$`` from having internal spaces set like blocks. 

The other point is that perltidy never changes the contents of quoted strings. Quoted items have to be changed by hand editing.

Since this has not been released to CPAN, I will consider changing the default to just ``-xbtl=k`` to minimize unexpected changes.


Incidentally, here is an little test case to verify that ``${`` can have the properties of a block:

```
   print ${ print "Hello "; \"World" }, "\n";
```

**Comment by Julien-Elie** [comment]
Many thanks for your answer.
I've just retested with `-xbt -xbtl=k` and the result is OK to me.  At least, the proposed changes do not surprise me :)

**Comment by shancock9** [comment]
Thanks for the comments. This will be in the next release to CPAN, expected to be in a week or two.
I've changed the default behavior of **-xbt** to just apply to braces around indirect objects which, as
discussed, has a lower 'surprise' factor.  This is  controlled by the parameter **xbtl** which has the 
revised description listed below.  The new default, in tagged version [20230309.04](https://github.com/perltidy/perltidy/tags), \
is equivalent to **-xbtl=k**.  The previous default can be obtained by setting **-xbtl=kt**. 

- **-xbtl=s**,   **--extended-block-tightness-list=s**

    The parameter **-xbt** can be made to apply to curly braces preceded by
    any of the keywords

        print printf exec system say

    and/or the special symbols

        $ @ % & * $#

    The parameter string **s** may contain a selection of these keywords and symbols
    to indicate the brace types to which **-xbt** applies.  For convenience, all of
    the keywords can be selected with 'k', and all of the special symbols
    can be selected with 't'.  The default is equivalent to **-xbtl='k'**, which
    selects all of the keywords.

    Examples:

        -xbtl='k'          # selects just the keywords [DEFAULT]
        -xbtl="t"          # selects just the special type symbols
        -xbtl="k t"        # selects all keywords and symbols, or more simply
        -xbtl="kt"         # selects all keywords and symbols
        -xbtl="print say"  # selects just keywords B<print> and B<say>:

    Here are some formatting examples using the default values of **-bt=n** and
    **-bbt=n**. Note that in these examples **$ref** is in block braces but **$key**
    is not.

        # default formatting
        print {*STDERR} $message;
        my $val = ${$ref}{$key};

        # perltidy -xbt           or
        # perltidy -xbt -xbtl=k
        print { *STDERR } $message;
        my $val = ${$ref}{$key};

        # perltidy -xbt -xbtl=t
        print {*STDERR} $message;
        my $val = ${ $ref }{$key};

        # perltidy -xbt -xbtl=kt
        print { *STDERR } $message;
        my $val = ${ $ref }{$key};

    Finally, note that this parameter merely changes the way that the parameter
    **--extended-block-tightness** works. It has no effect unless
    **--extended-block-tightness** is actually set.
