### ISSUE TITLE
Syntax error while linting, but no error when tidying

### ISSUE THREAD

**Issue by kevcenteno** [perltidy/perltidy#124]
Given:
```
...
return [
    gather while ( my $foo = $bar->foobar ) {
        ...
    }
];
```

We get this error: `syntax error at ') {', unexpected '{' after closing ')' of a trailing 'while'` when linting.

Flags: `--assert-tidy --no-standard-output --outfile=/dev/null`
perltidyrc: 
```
--blank-lines-before-packages=0
--iterations=2
--no-outdent-long-comments
--weld-nested-containers
-b
-bar
-boc
-ci=4
-i=4
-l=78
-nolq
-se
-wbb="% + - * / x != == >= <= =~ !~ < > | & >= < = **= += *= &= <<= &&= -= /= |= >>= ||= .= %= ^= x="
--character-encoding=utf8
--valign-exclusion-list="q"
--want-trailing-commas=m
--add-trailing-commas
--delete-repeated-commas
```

**Comment by shancock9** [comment]
The problem is that the ``gather`` operator introduces an extended syntax. I'm not familiar with it, but for example the version in Syntax::Keyword::Gather takes a block as an arg, which would imply something like:

```
    gather {
        while ( my $foo = $bar->foobar ) {
            ...;
        }
    }
```

I can easily bypass the syntax check, but before I make any changes, please verify that you are using your version of ``gather`` correctly.

**Comment by kevcenteno** [comment]
We're using `List::Gather` and looking at the docs, it allows for non-block args: https://metacpan.org/pod/List::Gather#gather

**Comment by horgh** [comment]
20230701 didn't have this issue by the way. We only saw it when updating to 20230909. We're on Perl 5.38.0.

**Comment by shancock9** [comment]
The error message was new with 20230909 to help catch some common errors caused by missing semicolons. The problem with this form of gather didn't get caught testing. I'll make an updated version without the check and that will fix the problem.

**Comment by shancock9** [comment]
Updating to version 20230912 at CPAN should fix this problem. Thanks for the report. Let's leave this issue open for a few weeks.

**Comment by horgh** [comment]
Thank you!

**Comment by kevcenteno** [comment]
I second horgh's comment.  Your prompt reply and attention is very much appreciated :smile:

**Comment by shancock9** [comment]
I think this can be closed now.
