### ISSUE TITLE
Flag to homogenize the use of parentheses

### ISSUE THREAD

**Issue by Julien-Elie** [perltidy/perltidy#128]
Would it be possible to add a flag to obtain a homogeneous style regarding the use of parentheses after functions calls, tokens like `if`, etc.?
For instance to force `open($ARTICLE, '<', $filename)` instead of `open $ARTICLE, '<', $filename`.
Same thing for `print("string")`, `defined($var)` etc.  I don't know which granularity should be used, especially when some people may want to exclude some functions or built-ins (like `print`) or when there's no arguments or when a block is expected (like for `map`, `sort`, `grep`...).

**Comment by shancock9** [comment]
Thanks for the suggestion. This would certainly be a useful option, but there would be significant difficulties in trying to implement it. It would easy to locate all instances where the existence or absence of parens is not in agreement with a desired scheme. And adding or deleting an opening paren after a certain keyword or function is straightforward. The difficulty is:  what to do about the closing paren.

If an existing closing paren is removed, and the paren is also serving as a logical container and is part of a logical expression and/or ternary expression, then simply removing the closing paren could change program behavior.

If a missing closing paren is to be added, it can be difficult to find the correct location if the function call is within a list, part of a ternary or logical expression, or contains parameters which themselves are user defined barewords whose prototypes are generally  unknown to perltidy.

So as useful as this option would be, I think it would be difficult or impossible to actually implement it with zero percent chance of introducing a program error.  It looks like the best that could be done would be to add a warning where the style disagrees with the desired style.

**Comment by Julien-Elie** [comment]
Thanks Steve for your comprehensive response.
I understand the problem.
I'm wondering whether the option could not automatically add the opening and closing parentheses when the syntax is totally unambiguous, with no room for interpretation.  And in case it needs more attention, just output a warning without changing anything.

**Comment by shancock9** [comment]
I'll think about it. I guess it depends on being able to setup good criteria for avoiding trouble. I need to look at a lot of examples.

**Comment by Julien-Elie** [comment]
Thanks Steve, I'll give it a try next week when I come back from holidays.
Looks promising.

I noticed 2 typos in the documentation: "may builtin" and "to to".  Also a single space after the end of a sentence if you wish to homogeneize.

Thanks again, and I wish you a happy new Year.

**Comment by Julien-Elie** [comment]
I've just tried 20230912.12.
The `-dmcp`, `-wcp` and `-nwcp` options work like a charm.  Very convenient to use; they are of help to spot an unwanted style, and then to (manually) carefully fix it.
Also tried the new `-duv` option, and I like it!

Thanks again for all your work on perltidy, Steve!

**Comment by shancock9** [comment]
Thanks for the testing and reporting. I hope to get the next release to CPAN in a couple of weeks.
I have been amazed at how many bugs and lines of dubious code I have found by running the new 
**-duv** option on existing code. I hope it gets widespread use. I even found 2 bugs in the 
perltidy source; fortunately both were benign.

**Comment by shancock9** [comment]
CPAN version 20240202 has been released with these new flags, so I will close this. Re-open it if there are any issues.
