### ISSUE TITLE
Another alignment challenge

### ISSUE THREAD

**Issue by tlhackque** [perltidy/perltidy#138]
Not sure if it's reasonable to expect perltidy to handle this better, but thought I'd pass it along.

Obviously, I know more about the semantics of the capture groups than perltidy can, but perhaps there's a heuristic for for creating an alignment group...  Or maybe a comment might provide a "ruler" with alignment points or other hints?

The `elseif` doesn't seem as challenging.

I don't particularly mind leaving the no format flags in this case, but you always seem to like a challenge...

**Input:** (This is manually formatted, and I think readable - for a regexp.  Obviously, I delete the `#<<<`/`#>>>` lines to run perltidy )
```perl
sub eui64 {
    my( $mac, $arg ) = @_;

    my @oct;
    #<<<
    if(      @oct = $mac =~ /^([[:xdigit:]]{1,2})([:-])([[:xdigit:]]{1,2})\2
                              ([[:xdigit:]]{1,2})\2    ([[:xdigit:]]{1,2})\2
                              ([[:xdigit:]]{1,2})\2    ([[:xdigit:]]{1,2})$/x ) {
        splice( @oct, 1,1 );
    } elsif( @oct = $mac =~ /^([[:xdigit:]]{2})        ([[:xdigit:]]{2})(\.?)
                              ([[:xdigit:]]{2})        ([[:xdigit:]]{2})\3
                              ([[:xdigit:]]{2})        ([[:xdigit:]]{2})$/x ) {
        splice( @oct, 2,1 );
    } else {
        die( "Invalid format for MAC address in $arg\n" );
    }

    return lc sprintf( "%02x%02s:%02sff:fe%02s:%02s%02s",
                       0x02 ^ oct("0x$oct[0]"),@oct[1..5] );
    #>>>
}
```
**Result:**
```perl
sub eui64 {
    my( $mac, $arg ) = @_;

    my @oct;
    if( @oct = $mac =~ /^([[:xdigit:]]{1,2})([:-])([[:xdigit:]]{1,2})\2
                              ([[:xdigit:]]{1,2})\2    ([[:xdigit:]]{1,2})\2
                              ([[:xdigit:]]{1,2})\2    ([[:xdigit:]]{1,2})$/x
        ) {
        splice( @oct, 1, 1 );
    } elsif(@oct = $mac =~ /^([[:xdigit:]]{2})        ([[:xdigit:]]{2})(\.?)
                              ([[:xdigit:]]{2})        ([[:xdigit:]]{2})\3
                              ([[:xdigit:]]{2})        ([[:xdigit:]]{2})$/x
        ) {
        splice( @oct, 2, 1 );
    } else {
        die( "Invalid format for MAC address in $arg\n" );
    }

    return lc sprintf(
            "%02x%02s:%02sff:fe%02s:%02s%02s",
            0x02 ^ oct( "0x$oct[0]" ), @oct[ 1 .. 5 ] );
}

```
Notes: The `elseif( ` loses the space after the left paren.  Whitespace within a `/x` regexp is ignored (unless quoted), so it can be adjusted freely.

A 'ruler' might be something like the following, meaning "create alignment block with the token-marking character(s) matching the next code line":
```perl
    #                    (                  (     (
    #                                       \
    if( @oct = $mac =~ /^([[:xdigit:]]{1,2})([:-])([[:xdigit:]]{1,2})\2
```
Not pretty (don't know how to do `[(\\]` in one column of a line, so I stacked), but comments are also allowed in `/x` patterns, so maybe?

I would guess that the `elseif` is fixable, the rest a challenge ...

**Comment by shancock9** [comment]
I used the perltidyrc.txt from git #134 to reproduce this.  The problem with the missing space after
``elsif(`` can be fixed by adding ``--extended-line-up-parentheses``, or ``-xlp``.  This is an
upgrade to the original ``-lp`` option, which was written to fix problems like this. The original
``-lp`` option did everything in a single pass and had limitations at something like a multi-line
quote. The ``-xlp`` version avoids this by making two passes through the file. 

So adding -xlp gives the following

```
# perltidy -pro=perltidyrc.txt -xlp
sub eui64 {
    my( $mac, $arg ) = @_;

    my @oct;
    if( @oct = $mac =~ /^([[:xdigit:]]{1,2})([:-])([[:xdigit:]]{1,2})\2
                              ([[:xdigit:]]{1,2})\2    ([[:xdigit:]]{1,2})\2
                              ([[:xdigit:]]{1,2})\2    ([[:xdigit:]]{1,2})$/x
        ) {
        splice( @oct, 1, 1 );
    } elsif( @oct = $mac =~ /^([[:xdigit:]]{2})        ([[:xdigit:]]{2})(\.?)
                              ([[:xdigit:]]{2})        ([[:xdigit:]]{2})\3
                              ([[:xdigit:]]{2})        ([[:xdigit:]]{2})$/x
        ) {
        splice( @oct, 2, 1 );
    } else {
        die( "Invalid format for MAC address in $arg\n" );
    }

    return
        lc sprintf( "%02x%02s:%02sff:fe%02s:%02s%02s",
                    0x02 ^ oct( "0x$oct[0]" ), @oct[ 1 .. 5 ] );
}
```

The ``elsif`` space problem is fixed. Also, the indentation of the ``sprintf`` args is improved. 
The alignment of the second and third lines of the first regex would have to be fixed by hand.

It would be very difficult to have perltidy adjust alignment within the regexes because they are
just handled as long quoted terms, even though there is a /x flag. The leading space
is not changed by perltidy, so it has to be changed by hand. The only quotes for which perltidy
changes leading spaces are ``qw`` quotes.

**Comment by tlhackque** [comment]
Sorry, didn't mean to make you guess.  Should have said the same `.perltidyrc` as #135 (not 134) -- plus -viu and -vwe as you suggested/implemented.

I've now added -xlp to my perltidyrc as well.

But I still see the `elsif` issue.  I verified that I'm using the updated .perlrc, shown below.

Perhaps it's the perltidy version that you cut with -vwe? 

FWIW: -lp is not over-riding -xlp (even though -xlp comes after -lp in .perlrc); same result if I comment-out -lp.

Attached is a tar archive with all the files (x.bak is input, x is output, the .perlrc is in the home directory):
[elsif.tar.gz](https://github.com/perltidy/perltidy/files/15019081/elsif.tar.gz)
```sh
perl 5.28.0 (Under perlbrew, if it matters)
This is perltidy, v20240202.03

strace -eopen perltidy -b x
gives (ignoring the perl stuff)

open("/root/.perltidyrc", O_RDONLY|O_LARGEFILE) = 4
open("x", O_RDONLY|O_LARGEFILE)         = 4
open("x", O_RDONLY|O_LARGEFILE)         = 4
open("x", O_RDONLY|O_LARGEFILE)         = 4
open("x.bak", O_WRONLY|O_CREAT|O_TRUNC|O_LARGEFILE, 0666) = 5
open("x", O_WRONLY|O_CREAT|O_TRUNC|O_LARGEFILE, 0666) = 4
```

Sounds like looking into the text of `/x `is too hard, as I suspected.  No problem.

Thanks.

P.S. I saw another issue where it was suggested that looking into the code of s/regex/code/e would be helpful, which seems loosely related.  I agree - though I find that unless the code is trivial, it's better to call a sub to do the work.  Clearer and `perltidy` can format. Code between "trivial" and "really too big" could benefit, though.

**Comment by shancock9** [comment]
If -xlp is given, then -lp is optional and is ignored.

I see what the problem is: The -xlp code which looks ahead to check for line length violations
should be ignoring the second and third lines of the regex, since it has no control over
their indentation, but it isn't doing that. I wrote a little patch to fix this. It seems to
work and I and will upload it after some testing. So thanks for finding a bug!

**Comment by shancock9** [comment]
A fix for this space issue with -xlp is in tagged version 20240202.07 at

https://github.com/perltidy/perltidy/tags

**Comment by tlhackque** [comment]
Thanks for the quick fix - sorry for the slow response (my email went thru a transition), so I just noticed it.

I'm closing the issue.
