### ISSUE TITLE
Inconsistent formatting of hash assignment

### ISSUE THREAD

**Issue by tomk3003** [perltidy/perltidy#14]
Source:

    $first = {
        key1 => 'aaa',
        key2 => 'bbb',
    } if $flag eq 'X';
    
    $second = {
        key1 => 'aaa',
        key2 => 'bbb',
    } if $flag1 or $flag2;

.perltidyrc:

    -st -se -w -ole=unix -l=100 -mbl=2 -i=4 -ci=4 -sot -wn -isbc -bar -otr -cab=0 -nolq -nola -nbbc -nsfs -nsak="my our local"

gives:

    my $first = {
        key1 => 'aaa',
        key2 => 'bbb',
    } if $flag eq 'X';
    
    $second = {
        key1 => 'aaa',
        key2 => 'bbb',
        } if $flag1
        or $flag2;

I would expect the second expression to be unchanged, too.

Tested with the latest version 20190601 under Strawberry-Perl 5.26.1.

**Comment by shancock9** [comment]
Yes, me too. I've written a patch to fix it and will include it if it
passes testing.
Steve

**Comment by shancock9** [comment]
version 20190915 has this fix
