### ISSUE TITLE
Use --longer options in man page discussions for better readability

### ISSUE THREAD

**Issue by jidanni** [perltidy/perltidy#144]
Actually the man page would be much more readable if the --longer versions of options were used instead of the shorter ones, in sentences like:

Before:

> The combination of -vmll and -wc=n provides a solution to the problem of displaying arbitrarily deep data structures and code in a finite window,

After:

> The combination of --variable-maximum-line-length and --whitespace-cycle=n provides a solution to the problem of displaying arbitrarily deep data structures and code in a finite window,

Especially as many readers are just swooping in for a quick glance.

Also many users are putting things in their .perltidyrc files, and not just typing on the bash command line, (which soon perhaps will have the --longer bash-completions added anyway.)

I'm not saying the man page must be 100% --longer options. 85% would be fine.

In fact these could also have long version too!:
```
s=never or   s=0 : no list should have a trailing comma
s=always or  s=1 or * : every list should have a trailing comma
...          s=m a multi-line list should have a trailing commas
             s=b trailing commas should be 'bare' (comma followed by newline)
             s=h lists of key=>value pairs, with about one one '=>' and one ',' per line,
                 with a bare trailing comma
             s=i lists with about one comma per line, with a bare trailing comma
             s=' ' or -wtc not defined : leave trailing commas unchanged [DEFAULT].
```

**Comment by shancock9** [comment]
Longer option names have been included in the man pages of the latest version, as suggested.
