### ISSUE TITLE
Allow older versions of perltidy to use newer .perltidyrc files

### ISSUE THREAD

**Issue by jidanni** [perltidy/perltidy#146]
Here I can use my .emacs file safely, no matter what version of emacs
I'm using.
```
$ cat .emacs
(and(functionp 'native-compile-prune-cache)
    (native-compile-prune-cache))
```
It would be great if .perltidyrc had a similar mechanism,
so I could say e.g.,
```
--if-implemented-yet -- --want-trailing-commas=1
--if-implemented-yet -- --add-trailing-commas
```
to avoid causing
```
Unknown option: want-trailing-commas
Unknown option: add-trailing-commas
Error in this config file: /home/jidanni/.perltidyrc
Use -npro to ignore this file, -h for help'
```
in the case I had used my newer .perltidyrc on a machine with an older perltidy.

Wait, https://www.perlmonks.org/?node_id=1165148 shows how to do it in
general in perl, so there could be something similar for .perltidyrc,
other than needing to have a different file for each different version
of perltidy.

Anyway, with my `--if-implemented-yet`, the user wouldn't even have to look up specific version numbers.

**Comment by shancock9** [comment]
A scheme like this would have had to have been implemented long ago to be
useful.

It would be possible to write a replacement script for the perltidy binary
which filters out unrecognized parameters from a ``.perltidyrc`` and sends a
modified version to the ``Perl::Tidy`` module.

But if a new binary is going to be involved, a simpler thing to do on a system
that you do not want to update would be to make a special binary with the latest
version and put it in your personal bin directory.  To do this, 

- download and unzip the latest tarball in a temporary area
- cd into the new folder
- enter ./pm2pl
- this creates a single file called something like ``perltidy-20240511.pl``
- move and rename this to something more convenient, perhaps ``~/bin/perltidy-latest.pl``

The installed version of the ``Perl::Tidy`` module will be unchanged, but the new 
binary does not use it

**Comment by jidanni** [comment]
> A scheme like this would have had to have been implemented long ago to be
useful.

Never too late to start :-).

(All I know is a simpleminded user like me just ends up temporarily commenting out stuff until all the systems I use eventually have versions that support it.)

**Comment by oalders** [comment]
This seems like a pretty niche case. I don't think it's unreasonable to make this the end user's problem to solve.

**Comment by shancock9** [comment]
I've tentatively added an option to do this by filtering a config file as follows: 
if a line in the config file begins with three dashes followed by a parameter name
(rather than two), then it will be removed if the parameter is not known. Otherwise,
a dash will be removed to make the line valid.  Older versions of perltidy will 
immediately stop if a parameter has three dashes.

I don't know if this will be very useful, since I don't anticipate adding many more
options to perltidy, but it was a simple change.

**Comment by Julien-Elie** [comment]
Why not a global `--allow-unknown-options` (`-auo`) option instead of having to add three dashes to each option?
I agree it will be useful only for perltidy versions starting from now.

**Comment by shancock9** [comment]
That would be equivalent to saying: "if I make spell any parameters incorrectly, just ignore them and don't tell me, just continue with the parameters that I managed to spell correctly." It would not end well.

**Comment by Julien-Elie** [comment]
It's like `-Wno-unknown-warning` for gcc or `-Wno-unknown-warning-option` for clang which are useful for this use case of several different users running the program but with no guarantee the version run by a given user recognizes all the passed flags.

**Comment by shancock9** [comment]
CPAN version 20240903 has the three-dash option discussed above for skipping an unimplemented parameter.

**Comment by jidanni** [comment]
I wish in .perltidyrc I could also do:

if($perltidy_version >= 20241111){
 bla
} else {
 goo
}
etc.

**Comment by shancock9** [comment]
A way to do this, without re-inventing the wheel, would be to let the ``perltidyrc``
file be generated by a perl script which used ``$Perl::Tidy::VERSION`` to decide on parameters.
The script might be named ``perltidyrc.pl``. Then perltidy could ``do perltidyrc.pl`` to get
the appropriate parameters. But this option would come with some security concerns, and
I don't want to go there. So the preprocessor script seems like the better option.
