### ISSUE TITLE
Can we get the latest tarball?

### ISSUE THREAD

**Issue by matthewpersico** [perltidy/perltidy#147]
Don't seem to find `https://cpan.metacpan.org/authors/id/S/SH/SHANCOCK/Perl-Tidy-20240511.02.tar.gz`. I could use the github repo, but my `$job` has processes in place to receive tarballs.

Thanks.

**Comment by shancock9** [comment]
Do you need this because of issue git #142, the install problem on versions before 5.10?

**Comment by shancock9** [comment]
The github tagged versions are tarballs, see:

https://github.com/perltidy/perltidy/tags

Uploads to CPAN are normally spaced by several months because they get much more
extensive testing and documenting. But this can be sped up for emergencies.

**Comment by matthewpersico** [comment]
> Do you need this because of issue git #142, the install problem on versions before 5.10?

No. I just figured that if there was a bug, I'd like to not have it. We are on > 5.10. Not by much though, unfortunately. Thanks!

**Comment by shancock9** [comment]
CPAN version 20240903 of perltidy is available and installs on Perl versions as early as 5.8.1.
