### ISSUE TITLE
Outputting the name of file if -duv reports something, and allow "u" in -wvt

### ISSUE THREAD

**Issue by Julien-Elie** [perltidy/perltidy#151]
Let's explain what I would like to achieve.
I have about 60 Perl files to process in the project.
To reformat them, I just give their name to `perltidy` and it does the job.

I would like to use **-duv** but if I run `perltidy -duv` on all the files, I just obtain an output like:

```
Issue abbreviations  u=unused  r=reused  s=multi-sigil  p=package crossing
Line:Issue: Var: note
418:u: my $msgid
Issue abbreviations  u=unused  r=reused  s=multi-sigil  p=package crossing
Line:Issue: Var: note
426:r: my $ago: reused - see line 417
575:s: my $buff: overlaps %buff in scope - see line 52
590:u: my $path
```

I would be interested to somehow have the name of the file for which the output is done.
I know I could run an `echo $filename && perltidy -duv $filename` but I would like not to echo the name when there's no output from `perltidy -duv`.  And I naturally could also first write the output of `perltidy -duv` to a temp file, check whether it is non empty, etc. but this seems overkill.  Could the name simply be added?  For instance along with `Line:Issue: Var: note for file.pl`.

Furthermore, I'm fine with the multi-sigil issue as it does not seem bad Perl style (at least to me) to use the same variable name between scalars, arrays and hashes if they contain the same data in a different format (`@users`, `%users`).  But I would like to see the other errors.
**-wvt** does not allow to do that ("u" cannot be specified).  Couldn't something be done to allow "u" to be used along with **-wvt**?

**Comment by shancock9** [comment]
I will add the filename to the output, that's a good idea.

The 'u' option was excluded from the options for the warning version because it has the
potential to create havoc, especially when formatting a small chunk of text with an editor.
For example, if the following line is sent to perltidy from within an editor,

```
my $self=shift;
```

and the 'u' option were enabled, then an error would be generated since it appears that
``$self`` is unused, since this is all that perltidy sees in this case.

And although the 'u' option is very useful for finding potential errors, almost all large
programs that I have examined have numerous variables reported as type 'u' which are
benign. For example, the perltidy source has 213 of them (and I consider them all perfectly fine).

So, to avoid having to deal with a lot of confusion, I prefer not to included it as a warning.

**Comment by Julien-Elie** [comment]
Thanks for your answer and the addition of the filename to the output.
As for **-wpt**, I understand well your point about a possible confusion when using "u" on chunks.  Couldn't it be allowed only when using **-duv**, and discarded otherwise?

`perltidy -duv -wpt="urp"`

**Comment by Julien-Elie** [comment]
A suggestion for the benign cases reported by "u", couldn't for instance `perltidy -duv` consider not as an error the variables suffixed with "_unused"?

`my ($userid, $name, $comment_unused, $group) = @_;`

would for instance not report `$comment_unused`.  It seems better to see it as-is for clarity for those who want, than forcing `undef` as the variable name to fix the report.

**Comment by shancock9** [comment]
It might be possible to allow the ``u`` option in ``-wvt=u`` only on the  command line, not in the config file,
and only when operating on a file (rather than stdin). In other words, under the same conditions as ``-duv``.
It would be a little unusual, but should get around most of the problems with editing, and with error messages
when running perlcritic, for example.  I'll consider this.

It should be possible to generalize the option ``--warn-variable-exclusion-list=s`` to allow a leading or trailing wildcard ``*``, 
so that ``--wvxl=*_unused`` would mean to match variables ending in ``_unused``.

**Comment by Julien-Elie** [comment]
That all sounds great.  Thanks, Steve.

**Comment by shancock9** [comment]
These updates are in tagged version 20240511.04 at

https://github.com/perltidy/perltidy/tags

**Comment by Julien-Elie** [comment]
Ah yes, understood.  It is because of `-duv`.  Couldn't the other flags also be taken into account when using `-duv`?

I confirm otherwise that the behaviour is correct:

```
% perltidy -wvt='p r u' -wvxl='*_unused' -se control/modules/ihave.pl
% perltidy -wvt='p r u' -wvxl='*_unused' -se contrib/analyze-traffic.in
```

No output, which is the expectation.  Thanks, Steve!
I can now easily process all my Perl files with the above command.

**Comment by shancock9** [comment]
Thanks for checking and verifying that these updates work.

To answer your question, the -dump and -warn commands really shouldn't be mixed,
so this would require adding new -dump controls which aren't really needed. The basic
idea of the various -dump parameters is to do a data dump to stdout in a simple format
which is easy to filter, or which can be manipulated in a spreadsheet. For example, the type 's' 
lines might be filtered from the dump output using

```
perltidy -duv match.pl | grep ":s:" -v
```

When there are corresponding -warn parameters, they generally must have additional
controls to avoid unwanted errors when formatting.

**Comment by Julien-Elie** [comment]
OK, I understand better the difference of use cases between dump and warn commands.  Likely, the additional controls you added like `-wmauc` which defaults to 4.

If I may suggest, to homogenize the output of the filename, I see that `-dbs` prints it (as well as `-duv` in the latest perltidy version).  Could the filename also be added to the output of `-dma` and `-dmcp`?

I have no other remarks; the new version totally fits my needs.

**Comment by shancock9** [comment]
Yes, I plan to add the filename to the other dump commands.

**Comment by Julien-Elie** [comment]
FYI to show you a concrete use of your latest addition of options, I enforced the following checks:

```
perltidy -se -wma -wmauc=0 -wmr -wvt='p r u' -wvxl='*_unused'
```

Changes can be found at:
- https://github.com/InterNetNews/inn/commit/a6661f22b24550bfd48789fd958f158eb46dc76c for `-wma -wmauc=0`;
- https://github.com/InterNetNews/inn/commit/b38b08ddb98c1651db00c53281bfef50e96b8e79 for `-wmr`;
- https://github.com/InterNetNews/inn/commit/beeaa337d3780812b27642a1370f72cd41039c40 for `-wvt='p r'`;
- https://github.com/InterNetNews/inn/commit/594f30d5ca90d6e587d1d054c340fddcc7b2efab for `-wvt='u' -wvxl='*_unused'`.

**Thanks again for all your work on perltidy!**

The next thing I'll look at is the homogenization of spaces and parentheses.  It's a tougher manual work for which I am currently considering `-nsak='my local our return' -wcp='*'` but I'll see what I can come up with.

**Comment by shancock9** [comment]
Thanks, it is nice to see these things are useful.  I like your ``_unused`` trick, it seems much nicer than
using ``void``, since that hides useful information.

**Comment by Julien-Elie** [comment]
I indeed began to remove unused variables in assignments by replacing them with `undef`, but after a few changes like that, I was under the impression I was somehow sabotaging the code.  Like you say, it hides useful information by no longer showing that the variable is readily available and could be used if needed.
That's why I asked for that feature in `-wvxl` and I am very grateful to you that you added it!
