### ISSUE TITLE
-xci uses a lower line length

### ISSUE THREAD

**Issue by Julien-Elie** [perltidy/perltidy#153]
`perltidy -boc -xci` rewraps the following second line whereas it has a length of 79 chars:

```
    my (
        $par, $sender, $replyto_unused, $site_unused, $action, $log, $approved,
        $article, $charset_from, $charset_to,
    ) = @_;
```

to:

```
    my (
        $par, $sender, $replyto_unused, $site_unused, $action, $log,
        $approved,
        $article, $charset_from, $charset_to,
    ) = @_;
```

Is it supposed to do that?  I would have expected the code to be unchanged as it fits in the length limit.

**Comment by shancock9** [comment]
Yes, this is an edge case at the line length limit. A number of operations
in perltidy, including ``-xci``, must employ tolerances of 1 or 2 characters to
avoid instability. The extra break does not occur with a length of 81 instead
of 80:

```
# perltidy -boc -l=81 -xci
my (
    $par,     $sender, $replyto_unused, $site_unused, $action, $log, $approved,
    $article, $charset_from, $charset_to,
) = @_;
```

**Comment by Julien-Elie** [comment]
OK, thanks Steve.  Wrapping can then occur in some cases at 1 or 2 characters less than the expected maximum length limit.  Couldn't this tolerance be mentioned in the documentation for `-l` for future reference?

**Comment by shancock9** [comment]
Sure, a note has been added.

**Comment by Julien-Elie** [comment]
Many thanks Steve.  The wording of the note is perfect.
