### ISSUE TITLE
Indenting arguments of functions used without parentheses

### ISSUE THREAD

**Issue by Julien-Elie** [perltidy/perltidy#155]
Following your recent suggestion that adding parentheses (in arithmetic operations) could improve the formatting, I've found out while adding parentheses to functions that indentation could be improved in multi-line lists like:

```
if (
    !open $FINDFILE,
    '-|',
    "find . \\( -type d -o -type f -o -type l \\) -name '[0-9]*' "
    . "-print 2>&1",
  )
{
    print "cannot start find in $spool";
}
```

which, with parentheses, is formatted like:

```
if (
    !open(
        $FINDFILE,
        '-|',
        "find . \\( -type d -o -type f -o -type l \\) -name '[0-9]*' "
          . "-print 2>&1",
    )
  )
{
    print "cannot start find in $spool";
}
```

Couldn't perltidy indent lines the same way, whether there were parentheses or not? (the arguments, and also the continuation line of the third argument)

**Comment by shancock9** [comment]
Adding parentheses can also significantly improve some complex logical statements.

I agree, it would be nice if this were possible. This is equivalent to the problem of
trying to add missing call parens. I looked at that (git #128) and found that it is too difficult to do.
So unfortunately, parens must be added and removed manually.

**Comment by Julien-Elie** [comment]
OK, I understand for the global indentation due to parentheses.
Is it the same for the following 2 lines from the above example, for which a second level of indentation is missing?

```
    "find . \\( -type d -o -type f -o -type l \\) -name '[0-9]*' "
    . "-print 2>&1",
```

**Comment by shancock9** [comment]
In this case, the ``if`` parens are a logical container and not a list container, so the extra continuation indentation given to list items does not occur.
