### ISSUE TITLE
New ^^ logical xor operator (Perl 5.40)

### ISSUE THREAD

**Issue by Julien-Elie** [perltidy/perltidy#157]
Perl 5.40 introduced a new syntax, `^^`, for the logical `xor` operator.  Could its knowledge be added to perltidy?

Incidentally, while having a look at the Perl 5.40 changelog, I see they also added a new `:reader` attribute:

`field $name :reader;`

perltidy currently adds a space after the colon, so it may be useful to also make it recognize attributes in general, which were added in a previous version (`:isa`, `:param`, `:inheritable`, ...).

**Comment by Julien-Elie** [comment]
Also noted while testing recent additions in Perl that `state($var);` is not reformatted with an additional space after the keyword.  According to the perltidy documentation, `state` is not a keyword.  Couldn't it be added in `-sak` as `my`, `local` and `our` already are?

**Comment by shancock9** [comment]
Yes, I just need to add ``^^`` to certain hashes to make it work.

I'm not sure why, but the built-in default is to put a space after an attribute
colon.  I might change that, but in any case it can be removed with
``--nowant-right-space=A`` or ``-nwrs=A``, where the ``A`` means attribute
colon.

Actually ``state`` was recently added as a keyword, and I just need to add it
to a list that ``-sak`` references to make the spacing work. I'll do that.

Thanks for the info.

**Comment by shancock9** [comment]
Tagged version 20240511.07 at

https://github.com/perltidy/perltidy/tags

has an update handle the new ``^^`` operator

**Comment by Julien-Elie** [comment]
Thanks for having added support for `state` and `^^`.  Just tested with 20240511.08.

Noted for the `--nowant-right-space=A` feature.  I do not manage to find where `A` is documented.  Probably worthwhile saying in the documentation, if not already present.

I would tend to think that the default should be without the colon for attributes.  When a colon is surrounded by spaces, it makes me think of a ternary operation.

**Comment by shancock9** [comment]
I've expanded the discussion on how to determine token types using this as an example:

    It is necessary to have a list of all token types in order to create
    this type of input.  Such a list can be obtained by the command
    **--dump-token-types**.  Also try the **-D** flag on a short snippet of code
    and look at the `.DEBUG` file to see the tokenization.
    
    To illustrate, suppose we do not want a space after a colon which introduces a
    sub attribute. We need to know its type. It is not a colon because that is the
    type of a ternary operator. The ouput of **--dump-token-types** states that it
    is token type 'A'.  To verify this, we can run `perltidy -D` on a short piece
    of code containing such a colon, such as
    
        sub foo : lvalue;
    
    This produces a `.DEBUG` file which contains
    
        1: sub foo : lvalue;
        1: SSSSSSSbAbwwwwww;
    
    The top line is the input, and the bottom line shows the token types.
    The 'A' beneath the colon verifies that it is type **A**.
    
    So to prevent a space on the right of this colon we can use
    
        # perltidy -nwrs='A'
        sub foo :lvalue;

I also prefer no space to the right. The default of a space was based on the
common usage when that token type was added to perltidy, as see for example in

https://perldoc.perl.org/attributes

**Comment by Julien-Elie** [comment]
Many thanks for the above documentation.  It is clear and very helpful.
