### ISSUE TITLE
Checking sub signatures for possible issues

### ISSUE THREAD

**Issue by Julien-Elie** [perltidy/perltidy#158]
Just noted an interesting new case for unused variables with sub signatures:

```
sub f ($var1, $var2) {
    return "$var1";
}
```

`-wvt='u'` could return that `$var2` is unused.  One could then declare `sub f ($var1, $)` or `sub f ($var1, $var2_unused)` with the `-wvxl='*_unused'` trick to suppress the warning.

Probably other interesting stuff could be checked with the variables in sub signatures (reuse, type...).

**Comment by shancock9** [comment]
Good idea, I'll see if I can implement this.

**Comment by shancock9** [comment]
Tagged version 20240511.07 at

https://github.com/perltidy/perltidy/tags

has an update to include sub signature variables in the check for unusal variables

**Comment by Julien-Elie** [comment]
Just tested with 20240511.08 and it looks fine.
