### ISSUE TITLE
nsbl with bl has no effect

### ISSUE THREAD

**Issue by ccruttjr** [perltidy/perltidy#159]
My `.perltidyrc` file is as follows

```
-bl
-nsbl
-l=120
```

My code starts as
```Perl
sub example{
my $ex = 0;
 if ( $ex){
    print "yay\n";}
}
```

I run `perltidy -b example.pl` and it formats it to
```Perl
sub example
{
    my $ex = 0;
    if ($ex)
    {
        print "yay\n";
    }
}
```
Even though I have the `-nsbl` flag. If I take out the `-bl` flag and leave the `-nsbl` flag I get
```Perl
sub example {
    my $ex = 0;
    if ($ex) {
        print "yay\n";
    }
}
```
And if I take out the `-bl` flag and change `-nsbl` to `-sbl` I get
```Perl
sub example
{
    my $ex = 0;
    if ($ex) {
        print "yay\n";
    }
}
```
So it seems all the flags work in conjunction except `-nsbl` with `-bl`.

**Comment by shancock9** [comment]
Yes, this is confusing; I'll see if I can clarify the documentation, and possibly the logic.
But **-bl** is the master switch, and the workaround is to just use **-bl** and specify
to which block types it should apply and/or which it should not apply.  For example,
the following tells it to apply to all block types except ``sub asub sort map grep eval``:

```
-bl
-bll='*'
-blxl='sub asub sort map grep eval'
```

This should give the result you are looking for.

**Comment by ccruttjr** [comment]
Sorry for the late response. It looks like what you said does do what I wanted!
```Perl
sub example {
    my $ex = 0;
    if ($ex)
    {
        print "yay\n";
    }
}
```
I don't see `bll` nor `blxl` on the style guide [perltidy.github.io/perltidy/stylekey.html](https://perltidy.github.io/perltidy/stylekey.html)

Thanks a ton.
