### ISSUE TITLE
Issues with vertical alignment in the latest release (20190915)

### ISSUE THREAD

**Issue by mgruner** [perltidy/perltidy#16]
We use Perl::Tidy with the following configuration: ```-l=120 -i=4 -ci=4 -vt=0 -vtc=0 -cti=0 -pt=1 -bt=1 -sbt=1 -bbt=1 -nsfs -nolq -bbao -nola -ndnl -cab=0```.

The previous release 20190601 formatted this code with expected vertical alignment of the ```=``` operator:

```
    my $Package   = $Self->RepositoryGet( %Param, Result => 'SCALAR' );
    my %Structure = $Self->PackageParse( String => $Package );
```
with the current release 20190915, we get instead (modifies the code to use no vertical alignment):

```
    my $Package = $Self->RepositoryGet( %Param, Result => 'SCALAR' );
    my %Structure = $Self->PackageParse( String => $Package );
```

Is this an intended change, or is there something we need to adopt in the configuration to keep the existing behaviour? Thank you very much for considering.

**Comment by shancock9** [comment]
This is a boarderline case of a two-line alignment match which got rejected but probably shouldn't have (the mismatched fat commas on the rhs are a factor here). I will tweak the alignment rules to fix it. There is no flag to fix it.

**Comment by shancock9** [comment]
This is fixed in v20191203

**Comment by mgruner** [comment]
Looks nice, thank you very much @shancock9!
