### ISSUE TITLE
Extend checks of unused constants to Readonly and :Constant

### ISSUE THREAD

**Issue by Julien-Elie** [perltidy/perltidy#161]
Could the `c` type in `--warn-variable-types` also take into account other ways to define constants than `use constant`?

I'm thinking about [Readonly](https://metacpan.org/pod/Readonly) which is a recommendation in the [ValuesAndExpressions::ProhibitConstantPragma](https://metacpan.org/pod/Perl::Critic::Policy::ValuesAndExpressions::ProhibitConstantPragma) _perlcritic_ policy.  I also see in the manual page of [constant](https://metacpan.org/pod/constant) links to the [: Constant attribute](https://metacpan.org/pod/Attribute::Constant) (with a space after the colon 😄 ) and [readonly](https://metacpan.org/pod/Scalar::Readonly) functions.

**Comment by shancock9** [comment]
Readonly variables can either be lexical or package variables:

Readonly lexical variables, which are preceded with the keyword ``my``, are already checked for issues like other ``my`` variables. This seems to be the main use of Readonly.  The issues which are checked by perltidy are independent of the Readonly attribute.

If a check for global variable issues is eventually added to perltidy, then Readonly global variables would be handled naturally as part of that check, along with varibles defined with ``our``, ``local``, ``use vars``, and possibly through some additional modules.

It looks like ``Attribute::Constant`` variables are lexical variables introduced with ``my``, so issues involving them should already covered.

**Comment by Julien-Elie** [comment]
Great to hear, thanks Steve for all your work.
