### ISSUE TITLE
Per-file directives

### ISSUE THREAD

**Issue by matthewpersico** [perltidy/perltidy#166]
I have a file that is a data file that gets 'do'ed into my perl .t test file. After running perltidy on it, there is one config that I want to change for just this file: --maximum-line-length=0.

I call perltidy in my github pre-commit hook. I have found no easy way to create an exception for just this file.

What I am thinking of is to add to perltidy such that this "works":
```
#<<C
#<<--cuddled-else
# "} else", not "}\nelse".

#<< --noblanks-before-comments
# Do NOT force a blank line before a full line comment.

#<<--ignore-side-comment-lengths
# Do not count the side comment in line-length calcs; comments won't cause line
# breaks.

#<<-nolq
# DON'T left slam long strings.

#<<-l=100
# Line length up from 80. Match Python standard.

#<<-vxl='q'
# Turn off aligning qw() for multiple 'use' statements. Was turned on by
# default in perltidy 20220613.

#>>C
```
In other words, you can have perl-file scoped  .perltidyrc by adding the specs to the file as comments, between `#<<C` and `#>>C` ('C' stands for "config).

Do you think you would take the patch if provided? Do you have a better suggestion for the syntax? Maybe something different than << and >> because those imply block scope and I am thinking these should be file scope, although if you wanted file scope, you could simply put the `#>>C` as the last line (or next to last if it's a module that has to end in `1;`)

**Comment by matthewpersico** [comment]
Other thoughts:

* If we go with these being block scoped then when you leave the block, the prior config values would apply.

* Do we need an `--ignore-infile-specs` flag?

**Comment by shancock9** [comment]
This would be useful, but I think it would be too difficult to implement, and
to implement without introducing some subtle bugs.  

The main problem is that before processing begins, a number of data structures are created
which depend on the various input parameters, and a lot of checking is done for
possible incorrect parameter values, and also with certain bad combinations of
parameters.  So if a parameter needs to be changed during processing, then
these data structures, and associated data checking, would need to be redone
while a file is being processed.  If an error is encountered, error recovery is
more complicated.

So I don't think this will work.

**Comment by matthewpersico** [comment]
Understood. If I get a few spare 'tuits' I'll play with it.
