### ISSUE TITLE
Something wrong with the distribution 20191203

### ISSUE THREAD

**Issue by zdm** [perltidy/perltidy#17]
By default cpanm always install previous version.
And I can install 20191203 only performing upgrade.
Maybe you forgot to update package version or it eas indexed incorrectly on CPAN?

**Comment by shancock9** [comment]
There were no indexing errors reported, and the version number was updated. So I don't see why that happened.

**Comment by zdm** [comment]
Do you also see this problem?

**Comment by shancock9** [comment]
I orignallly installed directly from the Makefile.  If I enter

sudo cpanm Perl::Tidy

I get

Perl::Tidy is up to date. (20191203)

since I already updated it.

Maybe someone else reading this can comment.

**Comment by zdm** [comment]
Seems, that it works now.
