### ISSUE TITLE
Shouldn't perltidy barf upon syntax errors like { b=> 5 c=> 6 }

### ISSUE THREAD

**Issue by jidanni** [perltidy/perltidy#18]
Shouldn't perltidy barf upon syntax errors like
`a => { b=> 5 c=> 6 }`

**Comment by shancock9** [comment]
Perltidy reports whatever errors it finds during formatting, but does not try to find all errors. Use perl -c to check your syntax.

**Comment by jidanni** [comment]
Yes but perltidy thinks
{
  b=> 5
  c=> 6
}
should become
{ b=> 5 c=> 6 }
which then needs more work to restore than just adding the comma. (Yes
we could add the comma and then run perltidy again.)

Yes we can alias perltidy to always do perl -c ... && perltidy... which
indeed will prevent mis-formatting due to syntax errors getting
mis-interpreted...

**Comment by shancock9** [comment]
version 20200619 has a check for this
