### ISSUE TITLE
missing 20200110 tag

### ISSUE THREAD

**Issue by kloczek** [perltidy/perltidy#21]
Looks like 20200110 version has not been tagged :)

**Comment by shancock9** [comment]
On my system 'git tag' gives:

20181117
20181119
20181120
20190601
20190915
20190915.01
20191203
20200110

so it looks like it got tagged

**Comment by kloczek** [comment]
Because probably you did not push those tags to github repo :)

Look on https://github.com/perltidy/perltidy/tags

**Comment by shancock9** [comment]
OK, thanks, I just did it.  Still learning git.

**Comment by kloczek** [comment]
ok so we close that issue :)

Thx
