### ISSUE TITLE
Continuation indentation seems broken here

### ISSUE THREAD

**Issue by mondash** [perltidy/perltidy#28]
I've run into an issue where continuation indentation isn't working as I would have expected. When the value for -ci is greater than or equal to the value of -i, I would expect lines with additional indentation to be indented relative to the new indentation level. Instead, those lines remain unchanged while those with no additional indentation are indented as specified by -ci. This becomes much more obvious when the value for -ci is much greater than that of -i. I've included several examples including the arguments I used for perltidy and the results I would have expected.

Is this behavior intended, and is it possible to fix? Thanks for you time!

```perl
# Using perltidy -npro -b (default -ci=2 -i=4)
# Actual and Expected
my $condition;

my $otherHashRef =
  $condition
  ? {
    'a' => 'a value',
    'b' => 'b value',
    'c' => {
        'd' => 'd value',
        'e' => 'e value'
    }
  }
  : undef;

# Using `perltidy -npro -ci=4 -b` (default -i=4)
# Actual
my $condition;

my $otherHashRef =
    $condition
    ? {
    'a' => 'a value',
    'b' => 'b value',
    'c' => {
        'd' => 'd value',
        'e' => 'e value'
    }
    }
    : undef;

# Expected
my $condition;

my $otherHashRef =
    $condition
    ? {
        'a' => 'a value',
        'b' => 'b value',
        'c' => {
            'd' => 'd value',
            'e' => 'e value'
        }
    }
    : undef;

# Using `perltidy -npro -ci=8 -b` (default -i=4)
#Actual
my $condition;

my $otherHashRef =
        $condition
        ? {
    'a' => 'a value',
    'b' => 'b value',
    'c' => {
        'd' => 'd value',
        'e' => 'e value'
    }
        }
        : undef;

# Expected
my $condition;

my $otherHashRef =
        $condition
        ? {
            'a' => 'a value',
            'b' => 'b value',
            'c' => {
                'd' => 'd value',
                'e' => 'e value'
            }
        }
        : undef;
```

**Comment by shancock9** [comment]
The concept of continuation indentation runs into a number of problems in complex statements, particularly when combined with ternary operators, and nested ternary operators, and nested ternary operators which contain code blocks which themselves contain continuation indentation, and so on.  I have been through many variations of coding -ci behavior, and the current version is the "least bad" survivor.  The main suggestion I can make is to use a value of -ci equal to about one-half of the value of -i, as recommended in the manual.

**Comment by mondash** [comment]
Thanks for your quick responses! We've been working to enforce tidiness on our code and would prefer to use `-ci=4 -i=4` is possible. Unfortunately we have many instances of that kind of structure with nested ternaries and code blocks. I understand you've worked hard on the issue in the past, but I'd really appreciate if you could keep it in mind to revisit at some point in the future when you have the time.

**Comment by shancock9** [comment]
I'll certainly keep this issue in mind, and appreciate the note.  It's just one of those really complex 'can of worms' that one doesn't like to re-open!

**Comment by Sadrak** [comment]
Hi,

this is also the last issue we are fighting to gain control about perltidy.

In our codebase we have often chained calls. Arguments within a later function call are not indented.

```perl
# -i=4, -ci=4
$obj
    ->this
    ->that(
    name => "baum",
    loc  => "x",
    );
```

Simpel adding additional params "fix" this problem:
```perl
# -i=4, -ci=4
$obj
    ->this
    ->that((
        name => "baum",
        loc  => "x",
    ));
```

Also addtional params "fix" the problem from mondash:

```perl
# Using `perltidy -npro -ci=4 -b` (default -i=4)
# Actual
my $condition;

my $otherHashRef =
    $condition
    ? ({
        'a' => 'a value',
        'b' => 'b value',
        'c' => {
            'd' => 'd value',
            'e' => 'e value'
        }
    })
    : undef;
```

ofc this breaks everything else ...
```perl
baum(
    haus((
            "haus" => "baum",
            baum   => "x",
        )),
);
```

We also would love to see a solution.

**Comment by shancock9** [comment]
I'm looking into a possible fix for this.

**Comment by shancock9** [comment]
I added a flag -xci to fix this problem.  It is in development version 20201001.01 which can be downloaded for testing from the 'Releases' page, https://github.com/perltidy/perltidy/releases

**Comment by Sadrak** [comment]
First small test looks good. I will make another test on monday with a bigger codebase.

shancock9++

**Comment by mondash** [comment]
Glad you're still looking into this issue! I should be able to do testing sometime next week.

**Comment by shancock9** [comment]
I discovered and fixed a few issues with the new -xci flag and uploaded them in version 20201001.02 which can be downloaded for testing from the 'Releases' page, https://github.com/perltidy/perltidy/releases.

**Comment by shancock9** [comment]
Version 20201202 has been released and has the -xci flag for correcting this problem.

**Comment by mondash** [comment]
@shancock9  Works great! Thanks for sticking with it. I appreciate it a lot! 😄

**Comment by Sadrak** [comment]
I encounter one strange behavior:

$ cat test.pl
```perl
http_post
    "http://...",
    $body,
    $headers,
    sub {
        if (...) {
            if (...) {
            }
        }
    }
;
```

$ perltidy -npro -st -cti=0 -ci=4 -i=4 test.pl
```perl
http_post
    "http://...", $body, $headers, sub {
    if (...) {
        if (...) {
        }
    }
    };

```

$ perltidy -npro -st -cti=0 -ci=4 -i=4 -xci test.pl
```perl
http_post
    "http://...", $body, $headers, sub {
        if (...) {
            if (...) {
        }
    }
    };
```

Again, with parenthesis for http_post everything is fine.

$ perltidy -npro -st -cti=0 -ci=4 -i=4 -xci test.pl
```perl
http_post(
    "http://...",
    $body, $headers,
    sub {
        if (...) {
            if (...) {
            }
        }
    }
);
```

**Comment by shancock9** [comment]
For subroutine calls without parens, perltidy will just format as a long statement, and this can come out poorly especially if there is an anonymous sub in the arg list.  Perltidy does not know the prototype for sub 'http_post' so it cannot fill in the missing parens.  Many programmers prefer to omit them, but I personally prefer not to because I have traced some subtle bugs to problems with sub calls which omitted parens.  Also note that Conway's book "Perl Best Practices" recommends using parens in sub calls.
