### ISSUE TITLE
Vertical alignment of similar lines

### ISSUE THREAD

**Issue by mondash** [perltidy/perltidy#29]
I'm a big fan of using valign to format hashes and keep fat commas aligned in a hash, but I find it to be a bit much for aligning similar lines since this sometimes produces code that's hard to read (see below).  I've tried using novalign to prevent this, but it doesnt seem to affect this kind of alignment (it does prevent valign for fat commas). I'd like to request a flag to disable valign for similar lines like this to prevent confusing code as seen in the last code snippet below. Thank you for your time!

```perl
my $longNameHashRef = {};

# perltidy -npro -b -ci=4
# Actual
if (   $longNameHashRef->{'someVeryWordyAttribute'}
    && $longNameHashRef->{'someOtherVeryWordyAttribute'} )
{
    print 'true';
}

#Desired
if ($longNameHashRef->{'someVeryWordyAttribute'}
    && $longNameHashRef->{'someOtherVeryWordyAttribute'} )
{
    print 'true';
}

# Paren alignment here is confusing
my $primaryAndSecondary = [
    grep {
        (              $longNameHashRef->{$_}->{'isPrimary'}
                    && $longNameHashRef->{$_}->{'someVeryWordyAttribute'} )
                || ( $longNameHashRef->{$_}->{'isSecondary'}
            && $longNameHashRef->{$_}->{'someOtherVeryWordyAttribute'} )
            }
            keys %$longNameHashRef;
];
```

**Comment by shancock9** [comment]
In the program, it is called "logical padding", and I can easily add a flag to skip it. I will try to get this in the next release for you.  Perhaps it can be called something like --logical-padding and --nological-padding.

**Comment by shancock9** [comment]
version 20200619 has the flag -nlop (--nological-padding) to prevent unwanted logical padding.
