### ISSUE TITLE
vertical alignment around `=~` is broken? 

### ISSUE THREAD

**Issue by bkarlson** [perltidy/perltidy#34]
Hello,

Looks like in the latest release (maybe in earlier too?) vertical alignment along `=~` is broken. 

Such code will stay unchanged:

```perl
	$v =~ s/(\d{1,3}?)(?=(\d{3})+$)/$1,/g;
	$va =~ s/(\d{1,3}?)(?=(\d{3})+$)/$1,/g;
	$var =~ s/(\d{1,3}?)(?=(\d{3})+$)/$1,/g;
	$vari =~ s/(\d{1,3}?)(?=(\d{3})+$)/$1,/g;
```

But the following one will be aligned correctly:

```perl
	$v    = s/(\d{1,3}?)(?=(\d{3})+$)/$1,/g;
	$va   = s/(\d{1,3}?)(?=(\d{3})+$)/$1,/g;
	$var  = s/(\d{1,3}?)(?=(\d{3})+$)/$1,/g;
	$vari = s/(\d{1,3}?)(?=(\d{3})+$)/$1,/g;
```

Cheers.

**Comment by shancock9** [comment]
I can't reproduce this with the current release, v20200619, or developmental version. Perhaps you are running an older version (use perltidy-v). The alignment of =~ was reactivated in version 20181120 after having been deactivated in some previous versions.
Steve

**Comment by bkarlson** [comment]
Yes, you're correct, my VSCode was using an old version of perltidy, switching to the new one solved the issue. Thanks heaps.
