### ISSUE TITLE
Some weird issues in UTF-8 handling

### ISSUE THREAD

**Issue by manchicken** [perltidy/perltidy#35]
Hey, I'm having two different UTF-8 issues which I think are related. I have a loose recollection of this working fine before, I think this may be recent as of Perl 5.32.

Keep in mind all of this is running on macOS Catalina.

Here's my `~/.perltidyrc`

```
 -ce
 -lp
 -cti=1
 -vt=1
 -pt=2
 -i=2
 -enc=utf8
```

I have tried this with and without `--use-unicode-gcstring`, and it seems to make no difference.

First, some basic unicode characters get mangled, such as this:

File: `foo-nowide.pl`

```perl
#!/usr/bin/env perl

use strict; use warnings;
use feature 'say';

say "«Hello!»";
```

Note the angle quotes in the call to `say()`. When I run `perltidy ./foo-nowide.pl`, this is the output:

```
⇒  perltidy ./foo-nowide.pl
#!/usr/bin/env perl

use strict;
use warnings;
use feature 'say';

say "�Hello!�";
```

Now, here's another interesting result that I get if I inject a wide character "数":

File: `foo-wide.pl`

```perl
#!/usr/bin/env perl

use strict; use warnings;
use feature 'say';

say "数 - «Hello!»";
```

When I run `perltidy ./foo-wide.pl`, this is the output:

```
⇒  perltidy ./foo-wide.pl
#!/usr/bin/env perl

use strict;
use warnings;
use feature 'say';

Wide character in print at /usr/local/Cellar/perl/5.32.0/lib/perl5/5.32.0/darwin-thread-multi-2level/IO/Handle.pm line 418.
say "数 - «Hello!»";
```

Notice that the output is fine, but there's a warning printed to `STDERR`.

This is a strange result, and I think it's related to the output stream not being opened as UTF-8 output.

I'm 100% open to the possibility that this is user error, but I don't see it. Many thanks.

**Comment by shancock9** [comment]
I assume that this problem has been fixed, so I will close the issue now.  I recommend updating to v20200907 which was released today.

**Comment by manchicken** [comment]
@shancock9 I can confirm that this was resolved. Sorry for the delay in confirmation.
