### ISSUE TITLE
Always break a line before (lonely) opening token (instead of after)

### ISSUE THREAD

**Issue by zweiter** [perltidy/perltidy#38]
Is there a way to break a line before any lonely brace on the right side?
I think it would be `--brace-left-and-indent` but not applied to a block but to any `opening-brace` that is 'right'.

```perl
# before perltidy
my %complex_hash = {
    string => 'value',
    array  => [ 1, 3, 3, 7 ],
    hash => {
              string => 'value',
              array  => [ 1, 3, 3, 7 ],
            }
} ;

#<<< after
my %complex_hash =
    {
    string  => 'value',
    array   => [ 1, 3, 3, 7 ],
    hash    =>
        {
        string => 'value',
        array  => [ 1, 3, 3, 7 ],
        }
    } ;
#>>>
```

**Comment by shancock9** [comment]
There is no flag to do that.  It may be possible to add a flag which, as a final step in processing, looks for lines
which end in an opening hash braces and adds a line break before them.  I'll look at it.

**Comment by zweiter** [comment]
@shancock9 Thanks a million for the update!

Could you also update the version on [CPAN](https://metacpan.org/pod/distribution/Perl-Tidy/bin/perltidy) please? This would enable me to share this bliss with the whole team easily.

**Comment by shancock9** [comment]
Sure, I'll try to get a new version out about Friday.

**Comment by shancock9** [comment]
Version 20201001 has been uploaded to cpan. The new flags -bbhb=n, bbsb=n, bbp=n are described in the man pages.
