### ISSUE TITLE
Vertical alignment of operators for which space is wanted around

### ISSUE THREAD

**Issue by zweiter** [perltidy/perltidy#39]
If an operator is padded with spaces I think it should be aligned as is done with the `function-paren` here:
```perl
# echo -e "\$poly->do_the('magic');\$morph->do_the('magic');" | perltidy --want-left-space="->" --want-right-space="->" --space-function-paren
$poly -> do_the  ('magic');
$morph -> do_the ('magic');
```

With usually space padded operators like `=` it's nicely aligned for both the operator and the parentheses:
```perl
$poly  = do_the ('magic');
$morph = do_the ('magic');
```

**Comment by shancock9** [comment]
This will be in the next release. A --want-left-space='->' parameter is sufficient to allow alignment.

**Comment by shancock9** [comment]
Version 20201001 at cpan will align an '->' with preceding space.
