### ISSUE TITLE
the option --break-at-old-logical-breakpoints don't preserve breakpoints

### ISSUE THREAD

**Issue by Sadrak** [perltidy/perltidy#42]
$ cat test.pl
```perl
if (
    foo()
    && bar()
    || (
        baz()
        or baf()
    )
    and bam()
) {
    print "yes!\n";
}
```
$ perltidy -npro -se -st -bol test.pl 
```perl
if (
    foo() && bar() || ( baz()
        or baf() )
    and bam()
  )
{
    print "yes!\n";
}
```

Perhaps i misunderstood this option, if so please make a docu improvement.

**Comment by shancock9** [comment]
I'll fix the docs. The -bol flag is the default and prevents perltidy from closing up the container (parens)
and making one long line, like this:  

```
# perltidy -nbol

if ( foo() && bar() || ( baz() or baf() ) and bam() ) {
    print "yes!\n";
}
```

But it doesn't copy the old line breakpoints. It would be possible to add a flag to do that.

**Comment by Sadrak** [comment]
We are currently using `-ndnl` to prevent every newline from deletion. This is useful for 2 situations: the one above and function arguments:

```perl
$obj->dothis(
    "foo",
    "bar",
    "baz",
);
```
I guess this is exactly the correct use for `-ndnl` and don't require an extra option.

The function argument is kind of annoying, because hash/hashrefs preserve the newlines (if there are some newlines).

**Comment by shancock9** [comment]
Version 20201202 has been released and has updated docs on the -bol flag.
