### ISSUE TITLE
Wide Unicode characters disrupt formatting

### ISSUE THREAD

**Issue by ddobbelaere** [perltidy/perltidy#43]
Formatted code sample (using `perltidy` with default arguments, v20201001):

```perl
use v5.30;
use warnings;
use utf8::all;

use Test::More tests => 3;

sub count_inner_chars {
    my ($S) = @_;
    my @a   = split /\s+/, $S;
    length join '', splice @a, 1, -1;
}

# Tests.
is count_inner_chars("The Weekly Challenge"),                    6;
is count_inner_chars("The purpose of our lives is to be happy"), 23;
is count_inner_chars("七、 八、 九、 十"),                              4;
```
Notice the incorrect formatting of the last line, which is 4 spaces off (EDIT: more like 5 actually), almost surely caused by the 4 (EDIT: actually, 7) Unicode characters preceding it.

**Comment by ddobbelaere** [comment]
Hmm, it seems it's not that easy as I portrayed. More careful investigation reveals that the used Chinese characters are 5/3 as wide as ASCII characters, but I really don't know why, i.e., if this a general rule (or how to solve the formatting issue if this is the case).

Unformatted text:

```perl
print "a", 1;
print "七", 1;
print "八", 1;
print "、", 1;
print "ab", 1;
print "abc", 1;
print "七七", 1;
print "abcd", 1;
print "七七七", 1;
print "abcde", 1;
print "七七七七七七七七七七七七", 1;
print "abcdeabcdeabcdeabcde", 1;
```

**Comment by shancock9** [comment]
For some reason I can't seem to copy the text of your messages, so I can't do any specific tests to check things. But I can make a couple of points.

First, if you are using the default options, be sure that the encoding was correctly guessed.  It should be, but just to be sure try adding the parameter '-utf8'.

In general, the display spacing depends on the display software, so it is not possible to always get perfect alignment in displayed output.  For example, I have noticed that if I view formatted files in the editor gedit, the alignment is often imperfect, whereas if I display the same files to the screen with the unix 'cat' command they are almost always perfectly aligned.  There is not much that can be done about this problem.

The spacing perltidy uses is defined by the module Unicode::GCString, which is the best that I am aware of. If something better becomes available it can easily be added as another option.

**Comment by ddobbelaere** [comment]
Thanks for your quick reply. The parameter `-utf8` leads to the same behavior, so the encoding was correctly guessed.

You are right that sometimes the display software screws things up. For example, Visual Studio Code (the editor I use mostly) "correctly" (I assume, as it follows the 3/5 rule of the linked Unicode spec. reference) renders the East Asian characters width. However, all Unicode spaces (even the "narrow" ones) have the same width as a single ASCII space...

Playing around a bit with `Unicode::GCString`, I notice that it considers `七` as either being 1 or 2 columns wide, depending on the value of the option `EAWidth`. Unfortunately, there is no "fractional" intermediate step followed by a rounding operation as the string `七七七` is either 3 or 6 characters wide, for all possible option AFAICS (should be 3*5/3 = 5 columns wide...).

Anyway, sorry for maybe pushing this too far, but I fear it's a dead end...

**Comment by shancock9** [comment]
I forgot to mention that you need to include the flag -gcs to make perltidy actually look for and use the Unicode::GCString module. So be sure you are doing that.

**Comment by ddobbelaere** [comment]
Ok, that explains a few things, using the `-gcs` flags leads to interpretation of the characters as 2 columns wide and to a correct formatting on my terminal (and in terminal based editors like vim)!

I guess it's just the rendering in Visual Studio Code (and also here on the rendered Github Markdown code blocks in my browser) that displays the characters as 5/3 columns, which is really impractical from a programming (and formatting) point of view. 

P.S.: the blog post https://denisbider.blogspot.com/2015/09/when-monospace-fonts-arent-unicode.html is an interesting read on this subject...

**Comment by shancock9** [comment]
I'm glad you resolved this problem, and thanks for the interesting link.  I wanted to make -gcs the default but during preliminary testing within a programming team we found that it caused confusion because people were getting different formatting results, depending on who had installed Unicode::GCString or not.  Making it a required flag eliminated the element of surprise.
