### ISSUE TITLE
-se breaks warnings exit status behavior

### ISSUE THREAD

**Issue by scop** [perltidy/perltidy#49]
> This is perltidy, v20201207 

```
$ echo 'print $$.$$' | perltidy -w ; echo $?
## Please see file perltidy.ERR
print $$.$$
2
```
This is good, exit status is 2. However:
```
$ echo 'print $$.$$' | perltidy -se -w ; echo $?

<stdin>: Begin Error Output Stream
<stdin>:1: operator in print statement not recommended
print $$.$$
0
```
Addition of `-se` causes exit status of 0.

This is problematic because for example in CI setups, editor integrations etc, `-se` is a good, common setting, and exit status zero may result in the output going unnoticed. Or even not shown at all, e.g. pre-commit suppresses tool output on success by default.

**Comment by shancock9** [comment]
Thanks. And it looks like the same problem happens if the user has set the -quiet flag.  I'll fix it.

**Comment by shancock9** [comment]
Version 20210111 has been released with an update to fix this.
