### ISSUE TITLE
Indented closing brace inside a method call

### ISSUE THREAD

**Issue by brtastic** [perltidy/perltidy#51]
Perltidy seem to misbehave for me in a single place, which is a `qw` inside a method call:
```
Type::Libraries->setup_class(
	__PACKAGE__,
	qw(
		Types::Standard
		Types::Common::Numeric
		), # <--- brace here
);
```
looks like it may be using continuation indentation in this place, however if I remove the rest of the code and only leave that `qw` in there, everything is formatted nicely:
```
	qw(
		Types::Standard
		Types::Common::Numeric
	);
```
My current options are as follows:
```
--maximum-line-length=120
--converge
--tabs
--entab-leading-whitespace=4
--continuation-indentation=4
--extended-continuation-indentation
--no-delete-old-newlines
--no-outdent-long-lines
--no-outdent-labels
--novalign
--no-logical-padding
--opening-sub-brace-on-new-line
--square-bracket-tightness=2
--paren-tightness=2
--brace-tightness=2
--opening-token-right

-sal='first any sum sum0 reduce'
```
As you can see I've already added a -xci flag from other issue but that did not solve my problem.
Thanks in advance!

**Comment by brtastic** [comment]
That semicolon is obviously helping perltidy format it better, so I've checked what happens if I add another `qw`:
```
Type::Libraries->setup_class(
	__PACKAGE__,
	qw(
		Types::Standard
		),
	qw(
		Types::Common::Numeric
		),
);
```
so it seems it understands that the statement ended there because the second qw is not indented. Without the method call, however:
```
qw(
	Types::Standard
	),
	qw(
	Types::Common::Numeric
);
```

**Comment by shancock9** [comment]
Thanks for catching that. I've fixed in in the development version so it will be fixed in the next release. Closing quote delimiters of qw quotes are not true container tokens so they have to be treated separately. The specific problem was that when an isolated closing quote delimiter was followed by a comma it should have followed the setting for the corresponding closing token, which by default (-cti=0) would remove the indentation.  I noticed and fixed a few other related issues.

**Comment by shancock9** [comment]
Version 20210111 has been released with an update to fix this.

**Comment by brtastic** [comment]
@shancock9 thank you for the new version. It indeed fixes the cases listed above, but it seems it doesn't work when qw() is not followed by a comma:
```
{
	modules => [
		qw(
			JSON
			)
	],
},
```

If a fill a comma after the closing brace, it places the paren in the right place

**Comment by shancock9** [comment]
The -no-delete-newlines flag was causing the problem. I've added a patch which fixes this and will reopen the issue and close when the next release is out.

**Comment by shancock9** [comment]
Version 20210401 has been released with a fix for this issue.
