### ISSUE TITLE
Vertical alignment of function call parentheses

### ISSUE THREAD

**Issue by zweiter** [perltidy/perltidy#53]
Currently there's only [one option to switch vertical alignment off](https://metacpan.org/pod/distribution/Perl-Tidy/bin/perltidy#Controlling-Vertical-Alignment).
Could there be an option to exclude function call parentheses from this rule to prevent long function names to move arguments far away from the function name?

```perl
# a little bit hard to read because the important information is far to the right
log_something_with_long_function ('This is a log message.') ;
Coro::AnyEvent::sleep            (3) ;
Throw                            ('error_indication') if ( $retries-- <= 0 ) ;

# function name and arguments can be seen as closely related at first glance
#<<<
log_something_with_long_function ( 'This is a log message.' ) ;
Coro::AnyEvent::sleep (3) ;
Throw ('error_indication') if ( $retries-- <= 0 ) ;
#>>>
```

**Comment by shancock9** [comment]
Sure, I'll either change the default behavior or add a control, or both.  The only little difficulty is designing a good control. I should note that this alignment is a side-effect of using the --space-function-paren control.

**Comment by shancock9** [comment]
Version 20210402 has been released. The new flag -nfpva will prevent this alignment.
