### ISSUE TITLE
Perltidy "remembers" errors when run multiple times

### ISSUE THREAD

**Issue by FractalBoy** [perltidy/perltidy#57]
I have a project that implements the Language Server Protocol, and uses perltidy to perform formatting.

It looks like it's only designed to ever run once per process, but my language server runs continuously and may call Perl::Tidy::perltidy multiple times.

If perltidy ever returns 2, it will always return 2 afterwards, even if there is no longer an error.

It looks like there is a variable, `$Warn_count`, that is only ever incremented and never reset. It would be nice if there were a way to reset this value so perltidy could be run again.

Right now, I am relying on whether STDERR is not empty. I could fork and pipe the formatted text back or callout to the command line utility, but I'd rather just keep everything in a single process if possible.

My solution seems to work just fine, but it is unintuitive that you could pass perfectly valid Perl code and still get a return value of 2.

**Comment by shancock9** [comment]
It will be fixed in the next release, which should be out near the end of this month.

**Comment by FractalBoy** [comment]
Thanks!

**Comment by shancock9** [comment]
Version 20210402 with an update to fix this has been released to CPAN. Thanks for reporting it.
