### ISSUE TITLE
Document how to format 'one liners' on the man page

### ISSUE THREAD

**Issue by jidanni** [perltidy/perltidy#58]
We've all heard about "great one liners". OK, let's say we've made a
great one liner (great for our garbage truck maps),
```
perl -wle '@f=(6790,2200); $ken_per_pixel=250/($f[0]+$f[1]);printf "%+.1f,%+.1f\n", 59250 + $f[0]*$ken_per_pixel, 37400+3*$ken_per_pixel;'
```
but we want to make it even greater, cosmetically.
We could, if --one-liner (or call it --single-line) were implemented.
Well, all I know is its output should look like:

```
$ set '@f=(6790,2200); $ken_per_pixel=250/($f[0]+$f[1]);printf "%+.1f,%+.1f\n", 59250 + $f[0]*$ken_per_pixel, 37400+3*$ken_per_pixel;'
$ echo $@|perltidy
@f             = ( 6790, 2200 );
$ken_per_pixel = 250 / ( $f[0] + $f[1] );
printf "%+.1f,%+.1f\n", 59250 + $f[0] * $ken_per_pixel,
  37400 + 3 * $ken_per_pixel;
$ echo $@|perltidy --one-liner
@f = ( 6790, 2200 ); $ken_per_pixel = 250 / ( $f[0] + $f[1] ); printf "%+.1f,%+.1f\n", 59250 + $f[0] * $ken_per_pixel, 37400 + 3 * $ken_per_pixel;
```
OK, if that is possible already, please document it on the man page.

What if --one-liner encounters a `#comment`? Well then it should refuse
to proceed, unless there is nothing after the comment. I.e., the comment
is on the last line of the input.

See also 
https://stackoverflow.com/questions/47692415/how-to-format-a-perl-oneliner

**Comment by shancock9** [comment]
You can use:

perltidy -l=0 -nanl

The first parameter sets the line length to infinity, and the second says do not add newlines

**Comment by jidanni** [comment]
@shancock9 that works great!
Perhaps it could be noted on the man page as how to do one-liners. Thanks.

**Comment by shancock9** [comment]
Sure. I have updated the manual section "Creating a new abbreviation" as follows:

For a specific example, the following line

        oneliner { -l=0 -nanl }

could be placed in a F<.perltidyrc> file to temporarily override the maximum
line length with a large value, and to temporarily prevent newlines from being
added.  All other settings in the F<.perltidyrc> file still apply.  Thus it
provides a way to format a long 'one liner' when perltidy is invoked with

        perltidy -oneliner ...

(Either C<-oneliner> or C<--oneliner> may be used).

**Comment by jidanni** [comment]
OK that's super! Except don't you think there should be two dashes in
> ```
>     perltidy -oneliner ...
> ```

Yes, even though


> (Either C<-oneliner> or C<--oneliner> may be used).

But don't you want to promote the two dashed version more?

**Comment by jidanni** [comment]
In fact to promote readability in .perltidyrc files, perhaps also first give
```
oneliner { --maximum-line-length=0 --noadd-newlines }
```

**Comment by jidanni** [comment]
@shancock9 Big problem. No way to replace code "in place" without it actually
becoming a two liner.
Nope, I tried all the "newline" related flags I could find.
It seems the moment one gives perltidy anything,

```
$ echo -n   | perltidy --oneliner | od -c
0000000
$ echo -n 1 | perltidy --oneliner | od -c
0000000   1  \n
0000002
```
it will always get a "bonus" newline added at back.

I.e., let's say I have three perl one-liners on one line of a Makefile.

Well then each time I use emacs' (C-u ESC |) shell-command-on-region, I have to
clean up the "bonus" newlines, three times.

**Comment by shancock9** [comment]
You can write a custom filter using the module Perl::Tidy and chomp the output rather than the binary perltidy. The manual has examples.  A minimal example might be something like

```
#!/usr/bin/perl -w
use strict;
use Perl::Tidy;
my $dest_string;
my $error = Perl::Tidy::perltidy(
    destination => \$dest_string,
);

if ($error) {
    die "Exiting because of serious errors\n";
}

if ($dest_string)      { 
    chomp $dest_string;
    print $dest_string;
}
```

**Comment by jidanni** [comment]
> You can write a custom filter using the module Perl::Tidy …

OK, but in any case, I have discovered, despite perltidy's --tons-of-switches, they forgot one!
The one to really, really stamp out newlines!
I mean one shouldn't need to haul in Perl::Tidy to zap one little \n.

**Comment by shancock9** [comment]
Version 20210625 is released with a flag that may help with this problem, --noadd-terminal-newline, -natnl.  When this is set, if the input stream does not have a terminal newline character, then none is added.
