### ISSUE TITLE
Fix warning: `Use of uninitialized value $Ktoken_vars in numeric eq (==) at /opt/perl5.32.1/lib/site_perl/5.32.1/Perl/Tidy/Formatter.pm line 5133.`

### ISSUE THREAD

**Issue by nchelluri** [perltidy/perltidy#67]
First create a file that will trigger the warning. `TidyThis.pm` has the following content:
```
#<<<
(
  'asdf',
  { some_key => 'some string' },
);
```

Double-checking the `perltidy` version:

```
$ perltidy --version
This is perltidy, v20210625 

Copyright 2000-2021, Steve Hancock

Perltidy is free software and may be copied under the terms of the GNU
General Public License, which is included in the distribution files.

Complete documentation for perltidy can be found using 'man perltidy'
or on the internet at http://perltidy.sourceforge.net.
```

Now making the bug occur:

```
$ perltidy TidyThis.pm 
Use of uninitialized value $Ktoken_vars in numeric eq (==) at /opt/perl5.32.1/lib/site_perl/5.32.1/Perl/Tidy/Formatter.pm line 5133.
```

It seems I can make the warning go away by adding a truthiness check to the conditional inside `if ($is_opening_token{$token} ) {` before using `$Ktoken_vars`:

```
                # Fix for case b1100: Count a line ending in ', [' as having
                # a line-ending comma.  Otherwise, these commas can be hidden
                # with something like --opening-square-bracket-right
                if (   $last_nonblank_type eq ','
                    && $Ktoken_vars # <--- this is my addition
                    && $Ktoken_vars == $Klast_old_code
                    && $Ktoken_vars > $Kfirst_old )
                {
                    $rlec_count_by_seqno->{$type_sequence}++;
                }
```

but I am not sure that is the right fix at all.

Can you take a look, please? Thank you.

**Comment by nchelluri** [comment]
P.S. I tried to report this on RT but with a guest account I didn't have permission. It wasn't clear to me where to post this, I hope this is okay.

**Comment by shancock9** [comment]
Thanks, 
This is the best place to post.

This got past testing and was fixed 4 July in the development version. It can happen when a format skipping comment begins before the first line of code in a file. Your fix will work but would be better written as 

```
&& defined($Ktoken_vars)
```
because a zero value is valid.

You can also download the latest development version 20210625.02 at 

https://github.com/perltidy/perltidy/releases/tag/20210625.02

Another workaround would be to move the first #<< line to after the first line of code.

Thanks for the report.  I will issue a new release soon.

**Comment by nchelluri** [comment]
Thanks for the quick response. I will await the new release.

**Comment by shancock9** [comment]
I'll leave this open for others to see and close it when the next release is out.

**Comment by shancock9** [comment]
Version 20210717 has been released with this issue fixed.
