### ISSUE TITLE
Perl-Tidy-20210717 does not check code compiles before running with this script.

### ISSUE THREAD

**Issue by squizzster** [perltidy/perltidy#71]
I am loving Perl-Tidy however for the script below I expect it to produce an error but it does not and outputs code which does not work as the source script already has an error.  I have tried other scripts with errors and it does not process them.  However for this source it does.  I do not know if this is by design but I don't think it can be.  Thank you for your contribution.

There should be a ";" on the end of the line:
`my $d_int = days_of_week_to_int (['zzz', 'Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'fri', 'SAT'])`

So this source script does not compile however Perl-Tidy does tidy it.

Is this correct?
Thank you,
Mark.

```use strict;
use feature qw(signatures);
use warnings;
no warnings qw(experimental::signatures);
#
my $DAYS_OF_WEEK_LOOKUP = ( { mon  =>  1, tue  =>  2, wed  =>  4, thu  =>  8, fri  => 16, sat  => 32, sun  => 64 });

my $d_int = days_of_week_to_int (['zzz', 'Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'fri', 'SAT'])
print "$d_int\n";

sub days_of_week_to_int ($days) {
  my $day_of_week = 0;
  foreach my $key (@$days)  {
    $day_of_week += $DAYS_OF_WEEK_LOOKUP->{lc($key)} if $DAYS_OF_WEEK_LOOKUP->{lc($key)};
  }
  return $day_of_week if $day_of_week < 128;
  return;
}
```

Final output:
` perl -c test/days_of_week.pl.tdy`

> syntax error at test/days_of_week.pl.tdy line 13, near ") print
> "
> test/days_of_week.pl.tdy had compilation errors.
>

**Comment by shancock9** [comment]
Perltidy is a code formatter, but it does catch many errors, especially missing or excess braces and parens.  It is not very good at catching missing semicolons.

**Comment by squizzster** [comment]
Fair enough.
The software is amazing.
Thank you for your expeditious response.

Mark

**Comment by squizzster** [comment]
Closed. Perl-Tidy worked as designed and it is great.
