### ISSUE TITLE
--line-up-parentheses does not work with subroutine definition in hash passed as parameter

### ISSUE THREAD

**Issue by ecos-platypus** [perltidy/perltidy#74]
When a subroutine definition is passed as part of a hash to a function, `--line-up-parentheses` does not work properly. What may be helpful: when passing an empty subroutine definition with a trailing comma, the alignment works properly.

See below for the relevant configuration options.

## Working formatting with regular hash

``` perl
$self -> func (
                {
                  command  => [ 'command', 'argument1', 'argument2' ],
                  callback =>
                      {
                        key0 => 'val0',
                      }
                }
              ) ;
```

## Expected formatting with subroutine definitions

``` perl
$self -> func (
                {
                  command  => [ 'command', 'argument1', 'argument2' ],
                  callback => sub
                      {
                      my ($res) = @_ ;
                      print ($res) ;
                      }
                }
              ) ;

$self -> func (
                {
                  command  => [ 'command', 'argument1', 'argument2' ],
                  callback => sub { }
                }
              ) ;

$self -> func (
                {
                  command  => [ 'command', 'argument1', 'argument2' ],
                  callback => sub { },
                }
              ) ;
```

## Actual formatting with subroutine definitions

``` perl
$self -> func (
    {
       command  => [ 'command', 'argument1', 'argument2' ],
       callback => sub
           {
           my ($res) = @_ ;
           print ($res) ;
           },
    }
) ;

$self -> func (
    {
      command  => [ 'command', 'argument1', 'argument2' ],
      callback => sub { }
    }
) ;

$self -> func (
                {
                  command  => [ 'command', 'argument1', 'argument2' ],
                  callback => sub { },
                }
              ) ;
```

## Relevant configuration options

``` bash
# Basic Options

--iterations=2
--maximum-line-length=120
--line-up-parentheses

# Code Indentation Control

--continuation-indentation=4
--closing-token-indentation=1

# Whitespace Control

--want-left-space="= -> ( )"
--want-right-space="= -> ( )"
--space-function-paren
--space-keyword-paren
--space-terminal-semicolon

# Line Break Control

--opening-brace-on-new-line
--opening-sub-brace-on-new-line
--opening-anonymous-sub-brace-on-new-line
--brace-left-and-indent
--brace-left-and-indent-list="*"
--break-before-hash-brace=3
```

**Comment by shancock9** [comment]
The problem in which -lp formatting was lost when a one-line anonymous sub was not followed by a comma has been fixed and will be in the next release. The update is in the most recent development version 20210717.04 at 
https://github.com/perltidy/perltidy/releases.

But if an anonymous sub is broken into multiple lines then the -lp indentation will still be lost.  This is basically the same issue as discussed in git #64, but in this case it is the forced line breaks due to the broken sub instead of side comments which are causing the loss of -lp formatting.

To illustrate, the following results are both possible with the specified parameters using the latest version, the first one has the anonymous sub written as a one-line block and the second one has it written in multiple-lines:


```
$self -> func (
                {
                  command  => [ 'command', 'argument1', 'argument2' ],
                  callback => sub { my ($res) = @_ ; print ($res) ; }
                }
              ) ;

$self -> func (
    {
       command  => [ 'command', 'argument1', 'argument2' ],
       callback => sub
           {
           my ($res) = @_ ;
           print ($res) ;
           }
    }
) ;
```

**Comment by ecos-platypus** [comment]
Thank you again for the quick fix. It is much appreciated!

With the comma issue fixed, we can use single-line subroutine definitions for most cases and define longer subroutines beforehand.

Regarding the multi-line issue: Should I close this issue and we keep track of the progress in #64?

**Comment by shancock9** [comment]
I'm glad I could help. Let's leave this open since the connection with git #64 is not so obvious.

**Comment by shancock9** [comment]
The next release to CPAN, which may be a few months away, will have a new flag -xlp (--extended-line-up-parentheses) which will remove the limitations on the -lp format in which it reverts to standard formatting at side comments, blank lines, and broken code blocks.  This new flag -xlp is off by default, to avoid changing existing formatting, so you need to set this flag to activate this feature.  

The main issue that I have noticed with this new flag is that the maximum line length can be sometimes be exceeded for deeply nested code, and code with very long identifiers or quotes.  I will see if I can minimize this problem.  But this has always been a problem with the -lp format, and it can be controlled somewhat by using a long maximum line length, and perhaps adding the -iscl flag (--ignore-side-comment-lengths) if there are very long side comments.

If anyone wants to test it, the interim tagged version 20211029.01 at github has the update:

https://github.com/perltidy/perltidy/releases/tag/20211029.01

**Comment by ecos-platypus** [comment]
Works like a charm. Thank you very much for the continued support!
