### ISSUE TITLE
--character-encoding=utf8 sad side effects

### ISSUE THREAD

**Issue by jidanni** [perltidy/perltidy#75]
Things looked good,
```
$ perltidy < m.pl
        if ( $s =~ /大茅埔段(３２５(０|４)|２９７５)|慶福街/ ) {
            $ruanbikeng++;
        }
        elsif ( $s =~ /大茅埔段３２(７|８|９).地/ ) {
            $zaokeng++;
        }
        else { next; }
```
until I tried --character-encoding=utf8,
```
$ perltidy --character-encoding=utf8 < m.pl
        if ( $s =~ /大茅埔段(３２５(０|４)|２９７５)|慶福街/ ) { $ruanbikeng++ }
        elsif ( $s =~ /大茅埔段３２(７|８|９).地/ ) {
            $zaokeng++;
        }
        else { next; }
```
(Yes, you might say "Well just don't use --character-encoding=utf8".)
$ perltidy -v
This is perltidy, v20200110

**Comment by shancock9** [comment]
Suggestion:  Upgrade to the latest version.  Install Unicode::GCString. Use --use-unicode-gcstring (-gcs).  Encoding is automatically detected now. The breaking of the short 'if' block, or lack of breaking, follows the input file if the line length permits.
