### ISSUE TITLE
Spurious leading space when aligning concatenated strings

### ISSUE THREAD

**Issue by Julien-Elie** [perltidy/perltidy#80]
The following code
```
logmsg("skipping $progname $type$sender"
     . " (pgpverify failed) in $curmsgid");
```
is reformatted:
```
logmsg( "skipping $progname $type$sender"
      . " (pgpverify failed) in $curmsgid");
```

Couldn't it be instead:

```
logmsg(
    "skipping $progname $type$sender"
  . " (pgpverify failed) in $curmsgid"
);
```

Note that _perltidy_ formats a similar concatenated string differently when there are several arguments: there is a line break after the initial parenthesis, and "." is indented as a continuation line of the first part of the string:
```
logger(
    $logname,
    "skipping $progname $type$sender"
      . " (pgpverify failed) in $curmsgid"
);
```

I suggest homogenizing the output of concatenated strings in these two forms.  It seems weird to see different formatting.

**Comment by Julien-Elie** [comment]
I've seen that adding `--nological-padding` removes the leading space, but the result is still
```
logmsg("skipping $progname $type$sender"
      . " (pgpverify failed) in $curmsgid");
```
Couldn't it be indented like the last example?

**Comment by shancock9** [comment]
The extra space is padding and  ```--nological-padding``` is indeed the flag to prevent it.

It looks like there are two additional issues: one is how to get the parens to break open, or stay broken open, and the other is to remove indentation of a '.'  to improve alignment.

It isn't possible to automatically break the parens open here, but it is possible to have perltidy keep them open if they are open in the input file with the flag 

```
    --keep-old-breakpoints-after='{', or kba='{'
```

The '{' here is the perltidy type of container tokens, so it matches the parens.

But 'outdenting' the lines with leading dots is not possible.  Any changes to indentation would almost certainly lead to problems with other controls.

**Comment by Julien-Elie** [comment]
Thanks for the suggestion as for the first issue.
My point about the second issue was the inconsistent indentation between _logmsg()_ and _logger()_ examples:

```
logmsg("skipping $progname $type$sender"
      . " (pgpverify failed) in $curmsgid");
```

I think the 6 leading spaces correspond to 4 (indentation) + 2 (continuation lines).  I'm using `-xci` (but `-nxci` does the same) and default values for indentation.
Why not only 2 for the indentation of the second line here?  (There still has not been a first indentation of 4, as the 1st line was not broken into 2 lines.)

Compared to this one, which I understand, where the continuation line of the 4th line is 2 more than the 3rd:

```
logger(
    $logname,
    "skipping $progname $type$sender"
      . " (pgpverify failed) in $curmsgid"
);
```

**Comment by Julien-Elie** [comment]
OK, thanks for the explanation.  Well, I think this ticket can be closed then.
