### ISSUE TITLE
Rewrapping of some constructions (labels, hash elements)

### ISSUE THREAD

**Issue by Julien-Elie** [perltidy/perltidy#86]
Wouldn't it be better to automatically rewrap constructions like:

```
  INPUT: while (<$IN>) {
        $line++;
        unless (($group, $hi, $lo, $f) = /^([^ ]+) (\d+) (\d+) (.+)\n$/) {
            eprint "$file:$line: malformed line.\n";
            next INPUT;
        }
    }
```

to

```
  INPUT:
    while (<$IN>) {
        $line++;
        unless (($group, $hi, $lo, $f) = /^([^ ]+) (\d+) (\d+) (.+)\n$/) {
            eprint "$file:$line: malformed line.\n";
            next INPUT;
        }
    }
```

and

```
    my %hash = {
        'a' => 'a',
        'b' => 'b',
        'c' => 'c', 'd' => 'd',
        'e' => 'e'
    };
```

to

```
    my %hash = {
        'a' => 'a',
        'b' => 'b',
        'c' => 'c',
        'd' => 'd',
        'e' => 'e'
    };
```

**Comment by shancock9** [comment]
On the first example, some people prefer a break after the label, and some don't. So the default behavior is to follow the input style, and keep a line break after the label if there was one in the input.  But it should be possible to add a flag to force a line break if it would be useful. 

On the second example, this is what is normally done unless there is a setting which prevents this from happening. You didn't include your settings, but for example the -boc flag tells perltidy to follow the input comma breakpoints and would prevent the default behavior.

**Comment by Julien-Elie** [comment]
Thanks for your answer.
A flag to add a break after the label (and maybe other constructions, if you have such in mind that people may have asked for in the past) would be useful I think.

You're right that `-boc` is used (full settings here: https://github.com/InterNetNews/inn/blob/main/.perltidyrc) because otherwise we see too many breaks that we do not want.  Using this flag explains the behaviour I saw, thanks!

**Comment by Julien-Elie** [comment]
I've just tested `-bal=1` and it performs exactly what I wanted.
Many thanks for having added that!
With the release of Perltidy 20220217, I believe this issue can now be closed.
