### ISSUE TITLE
Why is an operator in a print statement not recommended?

### ISSUE THREAD

**Issue by grahamc** [perltidy/perltidy#88]
I have this line of code which perltidy is unhappy about:

```
$info .= "URL: nar/" . basename $storePath . "\n";
```

```
30: operator in print statement not recommended
```
 
but I don't understand why it is not recommended. Can you help? Obviously I can "fix" this with:

```perl
my $basename = basename $storePath;
$info .= "URL: nar/" . $basename . "\n";
```

but I don't know what this is buying me.

**Comment by shancock9** [comment]
You are running an older version of perltidy. In the current version the message is

1: operator in possible indirect object location not recommended

This message is not an error message but does come out if you turn on -warnings. What is going 
on is that perltidy does not know what 'basename' is, so it is being cautious
and labeling the next token, $storePath, as a possible indirect object.  If it might be, then perl
may us spaces around the subsequent tokens to decide how to parse.  This can cause bugs which can be
hard to track down.

You can turn off warnings if this is annoying.

**Comment by shancock9** [comment]
I should have mentioned you can avoid the message by avoiding paren-less function calls

```
$info .= "URL: nar/" . basename($storePath) . "\n"

**Comment by grahamc** [comment]
Thank you @shancock9, this makes good sense to me!
