### ISSUE TITLE
Can't format chained block

### ISSUE THREAD

**Issue by elcamlost** [perltidy/perltidy#9]
I'm a new perltidy user and want to start using it in my project. But can't find settings, which won't break formatting until unreadable state.

For example, I have this code block.

```perl
sub event ($c, $query_params) {
    assert (ref $query_params eq 'HASH');
    assert (exists $query_params->{type});

    return Mojo::Promise->resolve(
        $query_params
    )->then(
        &_reveal_event
    )->then(
        \&_save_event
    )->then(
        \&_delegate_event
    )->then(sub ($code) {
        return $c->render(text => '', status => $code);
    })->catch(sub {
        # 1. return error
        return $c->render(json => {}, status => 400);
    });
}
```
after `perltidy -i=4 -ci=4` code looks like these.

```perl
sub _event ( $c, $query_params ) {
    assert( ref $query_params eq 'HASH' );
    assert( exists $query_params->{type} );

    return Mojo::Promise->resolve($query_params)->then(&_reveal_event)
        ->then( \&_save_event )->then( \&_delegate_event )->then(
        sub ($code) {
            return $c->render( text => '', status => $code );
        }
    )->catch(
        sub {
            # 1. return error
            return $c->render( json => {}, status => 400 );
        }
    );
}
```

So perltidy doesn't respect line breaks before `)->` construction and try to produce the longest line of chained invocations until line length limit.

Is there any option (except -fnl) I can use to preserve line breaks in this code snippet?

**Comment by shancock9** [comment]
I don't see a way to do this right now.

However, the next release has an option which does something similar for
lines with leading pointers.
('break-at-old-method-breakpoints',   or '-bom').  I've written a patch
which generalizes it to also work for this case
and I will include it if it passes testing.
Steve

**Comment by elcamlost** [comment]
Thanks, with new perltidy it works as expected.
-bom and absence of -iob options are required.
