### ISSUE TITLE
-et (entab) uses erroneously reads the -i setting when inserting tabs

### ISSUE THREAD

**Issue by rmzg** [perltidy/perltidy#90]
In short:
```
  1 sub hello {
  2 > print "hello world";
  3 }
```
Run through `:!perltidy -npro % -b -t -et=2 -nola` produces:
```
  1 sub hello {
  2 > > print "hello world";
  3 }
```
(Where `>` are representing tabs taking up two spaces)

After some investigation what is happening is it's comparing the `-et` setting of 2 to the default `-i` setting of 4 and since 2 + 2 = 4, it inserts 2 tabs. This behaviour is somewhere between "unintuitive" and "just plain broken". Specifying the number of spaces to convert into an indent level is one thing, but going the other way around and indenting multiple times to reach some guessed at display value is just hideously awful.

The entire point of the tab character is that it means "one indent level". You should never insert multiple tabs unless you actually mean to indent multiple levels, which my example clearly does not. Trying to pretend a tab has a width measurable in spaces instead of treating it as an abstract indent level makes for very weird bugs.

Suggested fix:
Aside from rewriting the program to understand indent levels as an abstract concept, at the very least tabs should ignore whatever `-i` is set to, especially since it has a default value.

**Comment by shancock9** [comment]
Sorry for the delayed response. For some reason this note did not get forwarded to me.

Try removing -et=2 because it conflicts with -t and has priority over the -t flag.

**Comment by rmzg** [comment]
You're right that removing `et` fixes it, my original approach involved using `-t` instead until I ended up using a tool that forced `-et` to be set. This might be a bug with the tool but it seems hard to argue with `This flag is retained for backwards compatibility, but if you use tabs, the -et=n flag is recommended.` from the documentation.

I think we can reasonably say that the documentation is somewhat confusing about which option you should be using when, but surely we can agree that even if you set `-et` and the code *already* has tabs then you shouldn't end up with extra tabs!

**Comment by shancock9** [comment]
Any existing tabs and other leading whitespace are stripped off before formatting begins, so they are not relevant.  Formatting produces leading whitespace which may be turned into tabs if requested. The example did not end up with extra tabs, it was obeying the -et=2 setting.

**Comment by rmzg** [comment]
Ok, then when would you use -et over -t like the docs say?

**Comment by shancock9** [comment]
The -t flag was replaced with -et=n many years ago because the concept 1 tab = 1 level is not complete. It remains to avoid breaking old parameter sets, but is not recommended.  One way to proceed is to first find parameters which work without tabs, so that the output looks okay if printed.  Then, set -et=n, where n is the value used for one indentation, set with -i=n. It has a default value of 4. But there is no standard definition of what a tab means, which is why tabs are not recommended, so display software may need to be adjusted.

**Comment by rmzg** [comment]
Thanks for the clarification update, it certainly helps. I'll note that I still think the fundamental idea of caring about spaces as opposed to indent levels is the opposite of how most users think, but this probably isn't the place to go further with that!
