### ISSUE TITLE
[feature request] vertical alignment of symbol list in use statements

### ISSUE THREAD

**Issue by XSven** [perltidy/perltidy#93]
This is perltidy, v20220217

How to tell perltidy to create this

```
use Log::Any         qw( $logger );
use Params::Validate qw( :types validation_options validate_pos );
use Scalar::Util     qw( refaddr );
```

instead of that

```
use Log::Any qw( $logger );
use Params::Validate qw( :types validation_options validate_pos );
use Scalar::Util qw( refaddr );
```

**Comment by shancock9** [comment]
This is not currently possible.

**Comment by XSven** [comment]
ok, maybe you can convert this question into a feature request.

**Comment by shancock9** [comment]
The next release can do this alignment. If needed sooner it is in the latest tagged version

https://github.com/perltidy/perltidy/releases/tag/20220217.03

**Comment by XSven** [comment]
It almost works:-( Sorry the above scenario was not as generic as it should have been. We are following the approach to always specify imports explicitly or to turn them off. At the same time we sort imports alphabetically. 

```
use Exporter         ();
use Log::Any         qw( $logger );
use Package::Stash   ();
use Params::Validate qw( :types validate validation_options validate_pos validate_with );
```

The requirement is to tell perltidy not to touch the alignment of () and qw() simultaneously. A compromise could be

```
use Exporter       ();
use Package::Stash ();

use Log::Any         qw( $logger );
use Params::Validate qw( :types validate validation_options validate_pos validate_with );
```
but then perltidy has to treat () in the same way as qw().

**Comment by shancock9** [comment]
The problem is that the vertical alignment logic only aligns similar things. So
what about replacing '()' with 'qw()', like this:

```
use Exporter         qw();
use Log::Any         qw( $logger );
use Package::Stash   qw();
use Params::Validate qw( :types validate validation_options validate_pos validate_with );
```

**Comment by shancock9** [comment]
Tagged version .04 has a patch to make empty parens () align with a qw in a use statement:

https://github.com/perltidy/perltidy/releases/tag/20220217.04

**Comment by XSven** [comment]
Works perfect! Thank you. Please feel free to close this issue after you have published a new release.

**Comment by shancock9** [comment]
This is in release v20220613 so this can be closed now.
