### ISSUE TITLE
Point releases are not pushed to CPAN

### ISSUE THREAD

**Issue by cheese** [perltidy/perltidy#94]
20220217.xx releases are tagged in Github but not pushed to CPAN.
Downstream projects like Fedora that tracks CPAN for new release will miss all the point releases.

**Comment by shancock9** [comment]
The next release to CPAN is expected to be in about one month.  The .xx versions typically contain features and updates being considered for the next release but they usually need some documentation work before final release to CPAN.

**Comment by cheese** [comment]
Point releases for pre-releases usually use scheme like xxx.90, xxx.91 and so on.
